/* Advent of Code day 7 */

/* 1. Set up tables */

drop table day7 purge;

create table day7 (
    seq_no number generated by default on null as identity,
    commands varchar2(50)
);
 
begin
    insert into day7 (commands) values('$ cd /');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir cmjgvh');
    insert into day7 (commands) values('dir czrzl');
    insert into day7 (commands) values('dir fcbt');
    insert into day7 (commands) values('dir hdh');
    insert into day7 (commands) values('259661 hjsbd.mzp');
    insert into day7 (commands) values('dir jgrdd');
    insert into day7 (commands) values('dir lqblqtng');
    insert into day7 (commands) values('dir pgvmpmn');
    insert into day7 (commands) values('dir pqqcvcm');
    insert into day7 (commands) values('dir zglbptq');
    insert into day7 (commands) values('$ cd cmjgvh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir hdh');
    insert into day7 (commands) values('134565 hdh.sjv');
    insert into day7 (commands) values('dir hgrpfmt');
    insert into day7 (commands) values('282147 mjtq.ffd');
    insert into day7 (commands) values('42343 rvmzv.rtb');
    insert into day7 (commands) values('dir sjgvbd');
    insert into day7 (commands) values('31468 wgtjmb.thf');
    insert into day7 (commands) values('$ cd hdh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('267125 htplc.gdw');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd hgrpfmt');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('39132 lndwz');
    insert into day7 (commands) values('280595 rffmsvdw');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd sjgvbd');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('26464 ghg.zmq');
    insert into day7 (commands) values('1533 zsgdbd.dmm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd czrzl');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir cmh');
    insert into day7 (commands) values('242795 hpgnd.mmt');
    insert into day7 (commands) values('157748 hps.ptg');
    insert into day7 (commands) values('129797 qjrhbjql.zdc');
    insert into day7 (commands) values('18290 sfhrzzcd.hwm');
    insert into day7 (commands) values('63141 sngg.vdw');
    insert into day7 (commands) values('$ cd cmh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir nglsj');
    insert into day7 (commands) values('dir szs');
    insert into day7 (commands) values('76775 vdpqhvrm.mcz');
    insert into day7 (commands) values('$ cd nglsj');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('307082 cjvph.fvc');
    insert into day7 (commands) values('286825 szs.vpj');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd szs');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('6233 fgpnnvm');
    insert into day7 (commands) values('94070 jjc.szq');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd fcbt');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('150417 grncq.brq');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd hdh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir cljdmh');
    insert into day7 (commands) values('dir fptsr');
    insert into day7 (commands) values('dir schjz');
    insert into day7 (commands) values('dir vrrcrhzs');
    insert into day7 (commands) values('$ cd cljdmh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir blsrsqz');
    insert into day7 (commands) values('21876 blthtcl');
    insert into day7 (commands) values('287047 cjvph.fvc');
    insert into day7 (commands) values('dir grncq');
    insert into day7 (commands) values('dir hdh');
    insert into day7 (commands) values('dir jdjps');
    insert into day7 (commands) values('dir mgzlprt');
    insert into day7 (commands) values('dir mrwc');
    insert into day7 (commands) values('33008 pcwnlp.czm');
    insert into day7 (commands) values('dir rdtdjb');
    insert into day7 (commands) values('135650 smf');
    insert into day7 (commands) values('173978 zsgdbd.dmm');
    insert into day7 (commands) values('$ cd blsrsqz');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('275130 dvqsffcn');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd grncq');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('213418 bhdpmv.zzt');
    insert into day7 (commands) values('153483 grncq.jsf');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd hdh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir dzrrh');
    insert into day7 (commands) values('dir gjjqhfq');
    insert into day7 (commands) values('231302 grncq');
    insert into day7 (commands) values('dir hdh');
    insert into day7 (commands) values('dir jnfczjjt');
    insert into day7 (commands) values('dir ljl');
    insert into day7 (commands) values('dir pwv');
    insert into day7 (commands) values('154659 rqvgf');
    insert into day7 (commands) values('dir vdvg');
    insert into day7 (commands) values('dir vpdqnv');
    insert into day7 (commands) values('$ cd dzrrh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir grncq');
    insert into day7 (commands) values('$ cd grncq');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('288753 grd');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd gjjqhfq');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir hdh');
    insert into day7 (commands) values('dir mnj');
    insert into day7 (commands) values('$ cd hdh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('241795 szs.mhq');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd mnj');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('200772 sfhrzzcd.hwm');
    insert into day7 (commands) values('237342 zsgdbd.dmm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd hdh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('30588 qptfqt.ggc');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd jnfczjjt');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('93796 rqbsqhp.grv');
    insert into day7 (commands) values('30301 sfhrzzcd.hwm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ljl');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir lvpvmlnb');
    insert into day7 (commands) values('dir tsb');
    insert into day7 (commands) values('227393 twnj');
    insert into day7 (commands) values('$ cd lvpvmlnb');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('16586 gnlmdb');
    insert into day7 (commands) values('340921 grncq');
    insert into day7 (commands) values('dir lqblqtng');
    insert into day7 (commands) values('dir nvp');
    insert into day7 (commands) values('$ cd lqblqtng');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('190888 dfjrnbwq');
    insert into day7 (commands) values('79149 dvqsffcn');
    insert into day7 (commands) values('dir grncq');
    insert into day7 (commands) values('267567 lqblqtng');
    insert into day7 (commands) values('169475 vzwm.pnd');
    insert into day7 (commands) values('305249 zsgdbd.dmm');
    insert into day7 (commands) values('$ cd grncq');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('323438 zjpg');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd nvp');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('239588 mffsww.qzc');
    insert into day7 (commands) values('dir qqhwjn');
    insert into day7 (commands) values('208451 qrjv.lns');
    insert into day7 (commands) values('34563 sfhrzzcd.hwm');
    insert into day7 (commands) values('$ cd qqhwjn');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('47343 wcpqgvh.cfl');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd tsb');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir lqblqtng');
    insert into day7 (commands) values('40229 szs');
    insert into day7 (commands) values('214138 whfw');
    insert into day7 (commands) values('$ cd lqblqtng');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('16005 fgpnnvm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd pwv');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir hzwljqm');
    insert into day7 (commands) values('51565 pjvpm');
    insert into day7 (commands) values('$ cd hzwljqm');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('106132 fgpnnvm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd vdvg');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('267870 zgm.wbw');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd vpdqnv');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir cmmc');
    insert into day7 (commands) values('239093 dvqsffcn');
    insert into day7 (commands) values('dir rhgb');
    insert into day7 (commands) values('142265 sfhrzzcd.hwm');
    insert into day7 (commands) values('dir szs');
    insert into day7 (commands) values('$ cd cmmc');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir pjhhbggb');
    insert into day7 (commands) values('$ cd pjhhbggb');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('195797 psqml.cjl');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd rhgb');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('102805 qrnntf');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd szs');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('314078 tcslpbc');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd jdjps');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('12330 twnj');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd mgzlprt');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('15552 gzthzjsr');
    insert into day7 (commands) values('dir hdh');
    insert into day7 (commands) values('dir qrfvn');
    insert into day7 (commands) values('dir twnj');
    insert into day7 (commands) values('331113 zsgdbd.dmm');
    insert into day7 (commands) values('$ cd hdh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir cfdrnjsg');
    insert into day7 (commands) values('343470 zsgdbd.dmm');
    insert into day7 (commands) values('$ cd cfdrnjsg');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir gddbd');
    insert into day7 (commands) values('309726 grncq.gmr');
    insert into day7 (commands) values('dir vzdfj');
    insert into day7 (commands) values('$ cd gddbd');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('226040 cjvph.fvc');
    insert into day7 (commands) values('47672 twnj');
    insert into day7 (commands) values('67109 zsgdbd.dmm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd vzdfj');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('29653 grncq');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd qrfvn');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('74136 lqblqtng');
    insert into day7 (commands) values('dir mjjrz');
    insert into day7 (commands) values('dir zrsz');
    insert into day7 (commands) values('$ cd mjjrz');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('27688 fgpnnvm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd zrsz');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('9100 wbrgdtv');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd twnj');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('41216 cjvph.fvc');
    insert into day7 (commands) values('250320 wnhjfm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd mrwc');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir bjwnmw');
    insert into day7 (commands) values('116091 grncq.phw');
    insert into day7 (commands) values('24868 hdh.lwn');
    insert into day7 (commands) values('29567 qsrtrvr.jbw');
    insert into day7 (commands) values('100251 szs.dvg');
    insert into day7 (commands) values('$ cd bjwnmw');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('128769 rdpsnm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd rdtdjb');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('132588 gsgjr');
    insert into day7 (commands) values('149600 lqblqtng.nnr');
    insert into day7 (commands) values('179302 wfbqblml.tgc');
    insert into day7 (commands) values('76170 wfrcm.fvp');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd fptsr');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('169594 lzlcml.mgm');
    insert into day7 (commands) values('dir zrc');
    insert into day7 (commands) values('dir ztd');
    insert into day7 (commands) values('$ cd zrc');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('110339 gjpgwrcm.lhg');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ztd');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('203770 zsgdbd.dmm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd schjz');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('3212 cjvph.fvc');
    insert into day7 (commands) values('288619 jcltshwj');
    insert into day7 (commands) values('295116 qmbp.mpd');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd vrrcrhzs');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir twnj');
    insert into day7 (commands) values('$ cd twnj');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('70492 dvqsffcn');
    insert into day7 (commands) values('44411 mhgspcgz');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd jgrdd');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('325202 dvqsffcn');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd lqblqtng');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir bbzv');
    insert into day7 (commands) values('dir gzqqp');
    insert into day7 (commands) values('dir vgt');
    insert into day7 (commands) values('$ cd bbzv');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('326190 fgpnnvm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd gzqqp');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('179929 crn.vpf');
    insert into day7 (commands) values('263365 dvqsffcn');
    insert into day7 (commands) values('251298 hdh.rsh');
    insert into day7 (commands) values('dir jgrtqpv');
    insert into day7 (commands) values('62514 lqblqtng.spm');
    insert into day7 (commands) values('dir njdhqsvj');
    insert into day7 (commands) values('32894 sfhrzzcd.hwm');
    insert into day7 (commands) values('$ cd jgrtqpv');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir bmvfszlz');
    insert into day7 (commands) values('286549 zsgdbd.dmm');
    insert into day7 (commands) values('$ cd bmvfszlz');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('169838 fgpnnvm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd njdhqsvj');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('2729 bgd');
    insert into day7 (commands) values('294119 fgcfbrdz.bll');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd vgt');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir btf');
    insert into day7 (commands) values('dir csgvtvsq');
    insert into day7 (commands) values('dir czbhw');
    insert into day7 (commands) values('dir jqnvscr');
    insert into day7 (commands) values('dir nqp');
    insert into day7 (commands) values('dir rlvnnmh');
    insert into day7 (commands) values('dir tmf');
    insert into day7 (commands) values('dir twjtnhll');
    insert into day7 (commands) values('$ cd btf');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('333891 cjvph.fvc');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd csgvtvsq');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir ccrvn');
    insert into day7 (commands) values('dir szs');
    insert into day7 (commands) values('dir tsmqm');
    insert into day7 (commands) values('dir tssfbq');
    insert into day7 (commands) values('$ cd ccrvn');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('14614 qbl.rjg');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd szs');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('92863 vswznzs');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd tsmqm');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('206954 dncrjt.sch');
    insert into day7 (commands) values('252714 zsgdbd.dmm');
    insert into day7 (commands) values('64306 zzr.snv');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd tssfbq');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('326310 chffstg.qcr');
    insert into day7 (commands) values('51533 cjvph.fvc');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd czbhw');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('290187 bdn.vjp');
    insert into day7 (commands) values('185832 cjvph.fvc');
    insert into day7 (commands) values('dir lqblqtng');
    insert into day7 (commands) values('198843 twnj.flf');
    insert into day7 (commands) values('64179 zjwg.jwc');
    insert into day7 (commands) values('256134 zrtmfn');
    insert into day7 (commands) values('$ cd lqblqtng');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('82035 cjvph.fvc');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd jqnvscr');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir bgqf');
    insert into day7 (commands) values('255437 dvqsffcn');
    insert into day7 (commands) values('147384 fzwzqb');
    insert into day7 (commands) values('dir gbf');
    insert into day7 (commands) values('dir gqzf');
    insert into day7 (commands) values('dir grncq');
    insert into day7 (commands) values('287135 grncq.pcg');
    insert into day7 (commands) values('333854 hqw.hgc');
    insert into day7 (commands) values('dir nzrsswd');
    insert into day7 (commands) values('dir svmqtq');
    insert into day7 (commands) values('$ cd bgqf');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('325037 jsv');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd gbf');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('274259 fgpnnvm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd gqzf');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('224386 hwwqrq.hcz');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd grncq');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir bvsfn');
    insert into day7 (commands) values('dir gcbzghtz');
    insert into day7 (commands) values('100460 njbgfrg');
    insert into day7 (commands) values('210677 phnslpqc.rbf');
    insert into day7 (commands) values('dir tgz');
    insert into day7 (commands) values('95034 vdpbwsn');
    insert into day7 (commands) values('dir vsrnbb');
    insert into day7 (commands) values('$ cd bvsfn');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('184581 lwj.gvm');
    insert into day7 (commands) values('dir pszwl');
    insert into day7 (commands) values('129220 sfhrzzcd.hwm');
    insert into day7 (commands) values('162987 smdvbnrq.zjd');
    insert into day7 (commands) values('71207 tspgccr.gdf');
    insert into day7 (commands) values('323030 zsgdbd.dmm');
    insert into day7 (commands) values('$ cd pszwl');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir szs');
    insert into day7 (commands) values('dir twnj');
    insert into day7 (commands) values('$ cd szs');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('341367 cbcvvtg.hcg');
    insert into day7 (commands) values('112908 rggrhm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd twnj');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('29609 sfhrzzcd.hwm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd gcbzghtz');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('139868 scggzqr.bzw');
    insert into day7 (commands) values('268881 smlhjltf.rwr');
    insert into day7 (commands) values('247122 wbwzdpg.djs');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd tgz');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('214842 grncq');
    insert into day7 (commands) values('dir njffnbp');
    insert into day7 (commands) values('dir sfvsdzs');
    insert into day7 (commands) values('dir sslvmwt');
    insert into day7 (commands) values('212789 szqph.gmw');
    insert into day7 (commands) values('$ cd njffnbp');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('243579 lmwd.mgz');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd sfvsdzs');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('7846 nthbtv.zdp');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd sslvmwt');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('241215 szs.rlb');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd vsrnbb');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('69152 cjvph.fvc');
    insert into day7 (commands) values('dir dvjmd');
    insert into day7 (commands) values('142844 dvqsffcn');
    insert into day7 (commands) values('242145 msm.nlf');
    insert into day7 (commands) values('dir nttvm');
    insert into day7 (commands) values('dir rjfjwbsm');
    insert into day7 (commands) values('47597 twnj.lft');
    insert into day7 (commands) values('123883 zsgdbd.dmm');
    insert into day7 (commands) values('$ cd dvjmd');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir lnhr');
    insert into day7 (commands) values('70772 qvs.gmv');
    insert into day7 (commands) values('80548 twnj.jdf');
    insert into day7 (commands) values('$ cd lnhr');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('202959 hdh');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd nttvm');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir hdh');
    insert into day7 (commands) values('$ cd hdh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('178915 fzgzdpbv.jdj');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd rjfjwbsm');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('114145 grncq');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd nzrsswd');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir bnrj');
    insert into day7 (commands) values('17967 cjvph.fvc');
    insert into day7 (commands) values('237712 fgpnnvm');
    insert into day7 (commands) values('dir spqqqd');
    insert into day7 (commands) values('dir szs');
    insert into day7 (commands) values('96651 twnj');
    insert into day7 (commands) values('6447 twnj.dft');
    insert into day7 (commands) values('$ cd bnrj');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('40924 cbhq.wpc');
    insert into day7 (commands) values('175930 cjvph.fvc');
    insert into day7 (commands) values('dir grncq');
    insert into day7 (commands) values('dir lfrtwv');
    insert into day7 (commands) values('267323 mmq.zwz');
    insert into day7 (commands) values('dir qsbmrs');
    insert into day7 (commands) values('dir wpsj');
    insert into day7 (commands) values('$ cd grncq');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('151440 ctmwl');
    insert into day7 (commands) values('83350 lqblqtng');
    insert into day7 (commands) values('145599 tpqfd.zfv');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd lfrtwv');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir cdzvst');
    insert into day7 (commands) values('144562 fgpnnvm');
    insert into day7 (commands) values('dir pllhlhr');
    insert into day7 (commands) values('dir qvdlrsw');
    insert into day7 (commands) values('$ cd cdzvst');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('211524 dvsnph.hrf');
    insert into day7 (commands) values('dir wchrhl');
    insert into day7 (commands) values('$ cd wchrhl');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('73032 lntqbfl.nbz');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd pllhlhr');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('70197 dtccz');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd qvdlrsw');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir gdmppfzv');
    insert into day7 (commands) values('$ cd gdmppfzv');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('244356 nhnsd');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd qsbmrs');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('155216 cvt.bdn');
    insert into day7 (commands) values('dir gcvlpg');
    insert into day7 (commands) values('dir hdh');
    insert into day7 (commands) values('$ cd gcvlpg');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('306542 bwnfl.rsl');
    insert into day7 (commands) values('67067 cjvph.fvc');
    insert into day7 (commands) values('341913 zsgdbd.dmm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd hdh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('138120 cjvph.fvc');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd wpsj');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('301391 sfhrzzcd.hwm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd spqqqd');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('40806 dvqsffcn');
    insert into day7 (commands) values('dir gqsbsmfm');
    insert into day7 (commands) values('41886 grncq.jqr');
    insert into day7 (commands) values('dir pdfsb');
    insert into day7 (commands) values('44167 pnq.nfr');
    insert into day7 (commands) values('127242 twnj.chn');
    insert into day7 (commands) values('125868 vvgzv.rmv');
    insert into day7 (commands) values('$ cd gqsbsmfm');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('99936 dvqsffcn');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd pdfsb');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('253190 fgpnnvm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd szs');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('164955 vswnnw');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd svmqtq');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir grncq');
    insert into day7 (commands) values('$ cd grncq');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('274192 hjdfj.qnw');
    insert into day7 (commands) values('dir tcrhb');
    insert into day7 (commands) values('dir twnj');
    insert into day7 (commands) values('$ cd tcrhb');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('64293 grncq.jvh');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd twnj');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('149048 cjvph.fvc');
    insert into day7 (commands) values('192053 rdgv');
    insert into day7 (commands) values('101473 zct.rmf');
    insert into day7 (commands) values('280169 zsgdbd.dmm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd nqp');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('107620 ndgz.gwb');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd rlvnnmh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('27340 gcpcffp.fqg');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd tmf');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('193196 fgpnnvm');
    insert into day7 (commands) values('22126 gwftf.wcr');
    insert into day7 (commands) values('92461 hdh');
    insert into day7 (commands) values('50807 qbdmzjd.jvg');
    insert into day7 (commands) values('dir qrrmhwn');
    insert into day7 (commands) values('dir rdcsmpfm');
    insert into day7 (commands) values('dir rgl');
    insert into day7 (commands) values('36742 zsgdbd.dmm');
    insert into day7 (commands) values('$ cd qrrmhwn');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir jgqzqhdc');
    insert into day7 (commands) values('109318 vtrtz.zvh');
    insert into day7 (commands) values('dir zmbtd');
    insert into day7 (commands) values('$ cd jgqzqhdc');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir zsdbppb');
    insert into day7 (commands) values('$ cd zsdbppb');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('325921 fgpnnvm');
    insert into day7 (commands) values('156452 tlcs.vzz');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd zmbtd');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('93641 bpzttjt');
    insert into day7 (commands) values('dir grncq');
    insert into day7 (commands) values('dir hdh');
    insert into day7 (commands) values('7832 shl.gbz');
    insert into day7 (commands) values('95398 twnj.fsd');
    insert into day7 (commands) values('$ cd grncq');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir qshl');
    insert into day7 (commands) values('$ cd qshl');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('312490 stqg.gwj');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd hdh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('225454 sfhrzzcd.hwm');
    insert into day7 (commands) values('265069 twnj.hfs');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd rdcsmpfm');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('72657 dvqsffcn');
    insert into day7 (commands) values('308572 fgpnnvm');
    insert into day7 (commands) values('dir hdh');
    insert into day7 (commands) values('dir lqblqtng');
    insert into day7 (commands) values('180474 lsgjgsrb.jfm');
    insert into day7 (commands) values('67774 ptpjjwc.bqn');
    insert into day7 (commands) values('$ cd hdh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('19858 sfhrzzcd.hwm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd lqblqtng');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('142164 cjvph.fvc');
    insert into day7 (commands) values('dir jpbh');
    insert into day7 (commands) values('dir prwnwvp');
    insert into day7 (commands) values('dir qbnthms');
    insert into day7 (commands) values('dir sthfhjf');
    insert into day7 (commands) values('$ cd jpbh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('167969 fgpnnvm');
    insert into day7 (commands) values('182107 jfzrww.tgb');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd prwnwvp');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir cczhv');
    insert into day7 (commands) values('70167 dvqsffcn');
    insert into day7 (commands) values('dir grncq');
    insert into day7 (commands) values('dir mbjwpdb');
    insert into day7 (commands) values('dir nll');
    insert into day7 (commands) values('dir qjjgjzbl');
    insert into day7 (commands) values('101178 qtqgcj');
    insert into day7 (commands) values('113714 sfhrzzcd.hwm');
    insert into day7 (commands) values('$ cd cczhv');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('158391 fmwzpjdm.nwz');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd grncq');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('238901 hdh');
    insert into day7 (commands) values('188528 mjwcd.bqt');
    insert into day7 (commands) values('61037 wpfg.shs');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd mbjwpdb');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir bphnpft');
    insert into day7 (commands) values('72033 fgpnnvm');
    insert into day7 (commands) values('dir hdh');
    insert into day7 (commands) values('dir qdmjnqc');
    insert into day7 (commands) values('dir rplsvs');
    insert into day7 (commands) values('85983 tpfjp');
    insert into day7 (commands) values('303863 wzwvbnw.blb');
    insert into day7 (commands) values('$ cd bphnpft');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('274331 gmmmlsj.pwp');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd hdh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('154778 szs.dtw');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd qdmjnqc');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('133639 grncq.wnj');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd rplsvs');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('332906 zpstcbj.zvt');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd nll');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('82368 cjvph.fvc');
    insert into day7 (commands) values('278280 ctmnzd');
    insert into day7 (commands) values('dir hdh');
    insert into day7 (commands) values('dir lqblqtng');
    insert into day7 (commands) values('211682 pshd.fds');
    insert into day7 (commands) values('319207 sfhrzzcd.hwm');
    insert into day7 (commands) values('46873 vrf.fgg');
    insert into day7 (commands) values('$ cd hdh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir hdtg');
    insert into day7 (commands) values('$ cd hdtg');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('19779 cjvph.fvc');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd lqblqtng');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('301792 dmhslp.hvz');
    insert into day7 (commands) values('305639 dvqsffcn');
    insert into day7 (commands) values('321833 strqtwrw');
    insert into day7 (commands) values('112471 twnj.fbn');
    insert into day7 (commands) values('20731 zsgdbd.dmm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd qjjgjzbl');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('78166 sztm.zrz');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd qbnthms');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('158365 bvwjvrvr.bvb');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd sthfhjf');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('239051 dvqsffcn');
    insert into day7 (commands) values('dir ghgcfwg');
    insert into day7 (commands) values('327346 glfcswq.cqc');
    insert into day7 (commands) values('dir tjqhqs');
    insert into day7 (commands) values('124072 twnj.cbn');
    insert into day7 (commands) values('261890 zsgdbd.dmm');
    insert into day7 (commands) values('28917 zvbn.rbz');
    insert into day7 (commands) values('$ cd ghgcfwg');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir szs');
    insert into day7 (commands) values('$ cd szs');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('29912 fgpnnvm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd tjqhqs');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('125555 twnj.dnv');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd rgl');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir grncq');
    insert into day7 (commands) values('59380 szs.jvh');
    insert into day7 (commands) values('dir wjjzprnz');
    insert into day7 (commands) values('$ cd grncq');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('283850 lqblqtng.cdf');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd wjjzprnz');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('339632 hbg.vpp');
    insert into day7 (commands) values('15887 zglntj.qtt');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd twjtnhll');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('207430 cjvph.fvc');
    insert into day7 (commands) values('dir dnv');
    insert into day7 (commands) values('dir hdh');
    insert into day7 (commands) values('232881 wwp');
    insert into day7 (commands) values('$ cd dnv');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('215966 lqblqtng.tdf');
    insert into day7 (commands) values('39850 szb.fqn');
    insert into day7 (commands) values('45436 twnj');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd hdh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir grrs');
    insert into day7 (commands) values('288906 hvjv');
    insert into day7 (commands) values('219092 mnr.qhg');
    insert into day7 (commands) values('336470 rwh');
    insert into day7 (commands) values('145474 sfhrzzcd.hwm');
    insert into day7 (commands) values('24384 szs.fwn');
    insert into day7 (commands) values('dir twnj');
    insert into day7 (commands) values('$ cd grrs');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('94496 dvqsffcn');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd twnj');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir sbhbnsw');
    insert into day7 (commands) values('$ cd sbhbnsw');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('162705 sfhrzzcd.hwm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd pgvmpmn');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('18511 sfhrzzcd.hwm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd pqqcvcm');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('201925 lqblqtng.mwb');
    insert into day7 (commands) values('300811 scjclwwz.bng');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd zglbptq');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir brhmv');
    insert into day7 (commands) values('237267 grncq');
    insert into day7 (commands) values('dir hdh');
    insert into day7 (commands) values('dir mhnfrn');
    insert into day7 (commands) values('131601 qtjwj');
    insert into day7 (commands) values('69185 tdtgmgw.qwc');
    insert into day7 (commands) values('96764 vppqqpf.znc');
    insert into day7 (commands) values('$ cd brhmv');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir ddd');
    insert into day7 (commands) values('dir dpnghvpp');
    insert into day7 (commands) values('102457 grncq');
    insert into day7 (commands) values('239654 jtvzhvd.jvm');
    insert into day7 (commands) values('276919 sfhrzzcd.hwm');
    insert into day7 (commands) values('235776 zsgdbd.dmm');
    insert into day7 (commands) values('$ cd ddd');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('dir grncq');
    insert into day7 (commands) values('dir mbrcgcd');
    insert into day7 (commands) values('$ cd grncq');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('110323 fgpnnvm');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd mbrcgcd');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('100317 pbb.hcb');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd dpnghvpp');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('259305 bscmwtd.mlw');
    insert into day7 (commands) values('dir hdh');
    insert into day7 (commands) values('$ cd hdh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('49708 grncq.zdl');
    insert into day7 (commands) values('dir szs');
    insert into day7 (commands) values('$ cd szs');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('225139 fgpnnvm');
    insert into day7 (commands) values('258801 twnj.nrj');
    insert into day7 (commands) values('dir wwzpvb');
    insert into day7 (commands) values('$ cd wwzpvb');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('4309 qlddd.cps');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd hdh');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('24775 hdh.htz');
    insert into day7 (commands) values('238695 jzpvhl');
    insert into day7 (commands) values('$ cd ..');
    insert into day7 (commands) values('$ cd mhnfrn');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('30250 sfhrzzcd.hwm');
    insert into day7 (commands) values('dir twnj');
    insert into day7 (commands) values('$ cd twnj');
    insert into day7 (commands) values('$ ls');
    insert into day7 (commands) values('244061 qddtlr.mpf');
end;
/

/* 2. Solutions */

with cleaned_up as (
    select 
        seq_no,
        case 
            when commands like '%..%'
            then 'move_back'
            when commands like 'dir%'
            then 'dir'
            when regexp_like(commands, '\d+')
            then 'file'
            when commands = '$ ls'
            then 'show'
            when regexp_like(commands, '\$\scd\s(\w+|\/)')
            then 'move_dir'
        end as subcata,
        case 
            when commands like 'dir%'
            then substr(commands, 5, length(commands))
            when regexp_like(commands, '\d+')
            then substr(commands, instr(commands, ' ', 1, 1) + 1, length(commands))
            when commands like '$ cd%' and commands not like '%..%'
            then substr(commands, 6, length(commands))
        end as contentname,
        regexp_substr(commands, '\d+') as file_size
    from day7
),
get_paths(curr_id, curr_size, path_history) as (
    select
        1,
        file_size,
        contentname
    from
        cleaned_up
    where
        seq_no = 1
    union all
    select
        get_paths.curr_id + 1,
        cleaned_up.file_size,
        case
            when cleaned_up.subcata = 'move_dir' and cleaned_up.contentname = '/'
            then get_paths.path_history
            when cleaned_up.subcata = 'move_dir' 
            then get_paths.path_history 
                    || ',' 
                    || substr(get_paths.path_history, instr(get_paths.path_history, ',', -1, 1) + 1, length(get_paths.path_history)) 
                    || '->' 
                    || cleaned_up.contentname
            when cleaned_up.subcata = 'move_back'
            then substr(get_paths.path_history, 1, instr(get_paths.path_history, ',', -1, 1) - 1)
            else get_paths.path_history
        end
    from 
        get_paths, cleaned_up
    where
        cleaned_up.seq_no = get_paths.curr_id + 1
),
breakup as (
    select 
        d.CURR_ID, 
        d.CURR_SIZE, 
        d.path_history, 
        case 
            when regexp_count(d.path_history, ',') = 0 
            then d.path_history
            else regexp_substr(d.path_history, '[^,]+', 1, d.loop_id)
        end as individual_path,
        d.loop_id
    from
        get_paths a
    cross apply
        (
            select 
                c.*,
                level as loop_id
            from
                ( select * from get_paths b where a.curr_id = b.curr_id ) c
            connect by 
                level <= regexp_count(c.path_history, ',') + 1
        ) d
),
rank_total as (
    select 
        individual_path, 
        sum(CURR_SIZE) as dir_total,
        30000000 - ( 70000000 - ( select sum(file_size) from cleaned_up ) ) as needed_space
    from 
        breakup 
    group by 
        individual_path 
),
part1 as (
    select 
        sum(dir_total) as answer_part1 
    from 
        rank_total 
    where 
        dir_total <= 100000
),
part2 as (
    select
        min(dir_total) as answer_part2
    from
        rank_total
    where
        DIR_TOTAL >= needed_space
)
select * from part1, part2
;