/*Advent of Code: Day 9 - Part 1 & 2 */

-- 1. Read the input, and break each move down into one step per row, so that later for each step we can calculate the positions of the heads and all the tails
drop table moves purge;
create table moves as 
    with raw_input(moves) as (
        select 'L 2' from dual union all
        select 'U 2' from dual union all
        select 'L 1' from dual union all
        select 'D 1' from dual union all
        select 'U 1' from dual union all
        select 'L 2' from dual union all
        select 'R 2' from dual union all
        select 'D 1' from dual union all
        select 'U 2' from dual union all
        select 'D 1' from dual union all
        select 'R 2' from dual union all
        select 'U 1' from dual union all
        select 'L 2' from dual union all
        select 'D 2' from dual union all
        select 'L 2' from dual union all
        select 'R 2' from dual union all
        select 'L 2' from dual union all
        select 'R 1' from dual union all
        select 'L 2' from dual union all
        select 'D 1' from dual union all
        select 'U 1' from dual union all
        select 'L 2' from dual union all
        select 'U 1' from dual union all
        select 'D 1' from dual union all
        select 'R 2' from dual union all
        select 'L 1' from dual union all
        select 'R 1' from dual union all
        select 'L 2' from dual union all
        select 'U 2' from dual union all
        select 'D 2' from dual union all
        select 'U 1' from dual union all
        select 'D 2' from dual union all
        select 'R 1' from dual union all
        select 'D 1' from dual union all
        select 'R 2' from dual union all
        select 'L 2' from dual union all
        select 'D 1' from dual union all
        select 'L 1' from dual union all
        select 'U 2' from dual union all
        select 'R 2' from dual union all
        select 'L 2' from dual union all
        select 'U 2' from dual union all
        select 'D 1' from dual union all
        select 'U 2' from dual union all
        select 'D 2' from dual union all
        select 'R 1' from dual union all
        select 'U 2' from dual union all
        select 'L 2' from dual union all
        select 'D 2' from dual union all
        select 'U 2' from dual union all
        select 'D 2' from dual union all
        select 'L 2' from dual union all
        select 'R 1' from dual union all
        select 'L 2' from dual union all
        select 'D 2' from dual union all
        select 'U 1' from dual union all
        select 'R 2' from dual union all
        select 'U 2' from dual union all
        select 'L 1' from dual union all
        select 'D 2' from dual union all
        select 'R 2' from dual union all
        select 'L 2' from dual union all
        select 'R 1' from dual union all
        select 'L 2' from dual union all
        select 'D 1' from dual union all
        select 'R 2' from dual union all
        select 'L 2' from dual union all
        select 'R 1' from dual union all
        select 'L 2' from dual union all
        select 'D 1' from dual union all
        select 'U 1' from dual union all
        select 'L 1' from dual union all
        select 'D 1' from dual union all
        select 'R 2' from dual union all
        select 'D 1' from dual union all
        select 'L 1' from dual union all
        select 'D 1' from dual union all
        select 'R 1' from dual union all
        select 'D 1' from dual union all
        select 'U 2' from dual union all
        select 'R 1' from dual union all
        select 'L 1' from dual union all
        select 'U 2' from dual union all
        select 'L 2' from dual union all
        select 'D 2' from dual union all
        select 'L 1' from dual union all
        select 'U 1' from dual union all
        select 'D 1' from dual union all
        select 'L 1' from dual union all
        select 'U 1' from dual union all
        select 'D 1' from dual union all
        select 'U 1' from dual union all
        select 'R 2' from dual union all
        select 'L 2' from dual union all
        select 'U 2' from dual union all
        select 'R 2' from dual union all
        select 'L 2' from dual union all
        select 'D 2' from dual union all
        select 'U 1' from dual union all
        select 'L 1' from dual union all
        select 'R 1' from dual union all
        select 'U 2' from dual union all
        select 'R 1' from dual union all
        select 'D 2' from dual union all
        select 'R 1' from dual union all
        select 'L 2' from dual union all
        select 'R 2' from dual union all
        select 'U 2' from dual union all
        select 'D 2' from dual union all
        select 'R 1' from dual union all
        select 'U 2' from dual union all
        select 'L 2' from dual union all
        select 'R 1' from dual union all
        select 'L 2' from dual union all
        select 'D 3' from dual union all
        select 'L 3' from dual union all
        select 'D 3' from dual union all
        select 'L 3' from dual union all
        select 'U 3' from dual union all
        select 'D 2' from dual union all
        select 'R 2' from dual union all
        select 'D 3' from dual union all
        select 'L 1' from dual union all
        select 'R 2' from dual union all
        select 'D 2' from dual union all
        select 'R 2' from dual union all
        select 'D 3' from dual union all
        select 'U 3' from dual union all
        select 'D 1' from dual union all
        select 'R 2' from dual union all
        select 'D 3' from dual union all
        select 'L 1' from dual union all
        select 'D 1' from dual union all
        select 'L 1' from dual union all
        select 'D 3' from dual union all
        select 'R 2' from dual union all
        select 'U 2' from dual union all
        select 'D 3' from dual union all
        select 'R 2' from dual union all
        select 'U 2' from dual union all
        select 'D 2' from dual union all
        select 'L 2' from dual union all
        select 'U 1' from dual union all
        select 'R 3' from dual union all
        select 'U 2' from dual union all
        select 'D 3' from dual union all
        select 'U 1' from dual union all
        select 'R 2' from dual union all
        select 'D 2' from dual union all
        select 'U 2' from dual union all
        select 'D 1' from dual union all
        select 'R 2' from dual union all
        select 'D 2' from dual union all
        select 'R 3' from dual union all
        select 'L 1' from dual union all
        select 'R 1' from dual union all
        select 'L 1' from dual union all
        select 'D 2' from dual union all
        select 'U 3' from dual union all
        select 'R 2' from dual union all
        select 'U 2' from dual union all
        select 'L 1' from dual union all
        select 'R 1' from dual union all
        select 'U 3' from dual union all
        select 'L 3' from dual union all
        select 'D 2' from dual union all
        select 'R 2' from dual union all
        select 'L 1' from dual union all
        select 'U 2' from dual union all
        select 'R 3' from dual union all
        select 'D 3' from dual union all
        select 'U 2' from dual union all
        select 'D 3' from dual union all
        select 'R 2' from dual union all
        select 'U 2' from dual union all
        select 'D 2' from dual union all
        select 'L 1' from dual union all
        select 'D 3' from dual union all
        select 'U 1' from dual union all
        select 'L 2' from dual union all
        select 'R 2' from dual union all
        select 'L 2' from dual union all
        select 'R 1' from dual union all
        select 'L 1' from dual union all
        select 'R 3' from dual union all
        select 'L 2' from dual union all
        select 'U 1' from dual union all
        select 'D 2' from dual union all
        select 'U 2' from dual union all
        select 'L 2' from dual union all
        select 'U 2' from dual union all
        select 'L 3' from dual union all
        select 'U 2' from dual union all
        select 'D 3' from dual union all
        select 'U 1' from dual union all
        select 'L 3' from dual union all
        select 'D 3' from dual union all
        select 'U 2' from dual union all
        select 'D 2' from dual union all
        select 'L 1' from dual union all
        select 'U 2' from dual union all
        select 'D 2' from dual union all
        select 'L 3' from dual union all
        select 'D 3' from dual union all
        select 'R 2' from dual union all
        select 'L 1' from dual union all
        select 'U 3' from dual union all
        select 'L 3' from dual union all
        select 'D 2' from dual union all
        select 'L 2' from dual union all
        select 'R 2' from dual union all
        select 'D 1' from dual union all
        select 'L 2' from dual union all
        select 'D 1' from dual union all
        select 'R 2' from dual union all
        select 'L 1' from dual union all
        select 'U 3' from dual union all
        select 'R 2' from dual union all
        select 'L 3' from dual union all
        select 'R 1' from dual union all
        select 'L 1' from dual union all
        select 'R 3' from dual union all
        select 'L 2' from dual union all
        select 'R 2' from dual union all
        select 'U 2' from dual union all
        select 'D 4' from dual union all
        select 'L 3' from dual union all
        select 'U 3' from dual union all
        select 'L 4' from dual union all
        select 'U 2' from dual union all
        select 'L 2' from dual union all
        select 'U 3' from dual union all
        select 'R 2' from dual union all
        select 'U 4' from dual union all
        select 'R 1' from dual union all
        select 'U 3' from dual union all
        select 'R 1' from dual union all
        select 'U 4' from dual union all
        select 'L 3' from dual union all
        select 'R 4' from dual union all
        select 'L 4' from dual union all
        select 'U 3' from dual union all
        select 'D 1' from dual union all
        select 'R 2' from dual union all
        select 'D 4' from dual union all
        select 'U 1' from dual union all
        select 'D 3' from dual union all
        select 'R 2' from dual union all
        select 'U 2' from dual union all
        select 'R 1' from dual union all
        select 'L 4' from dual union all
        select 'R 2' from dual union all
        select 'L 3' from dual union all
        select 'U 4' from dual union all
        select 'D 4' from dual union all
        select 'R 4' from dual union all
        select 'U 1' from dual union all
        select 'R 2' from dual union all
        select 'D 3' from dual union all
        select 'U 1' from dual union all
        select 'L 1' from dual union all
        select 'U 3' from dual union all
        select 'L 1' from dual union all
        select 'R 1' from dual union all
        select 'U 2' from dual union all
        select 'R 4' from dual union all
        select 'D 2' from dual union all
        select 'U 1' from dual union all
        select 'D 3' from dual union all
        select 'U 4' from dual union all
        select 'L 1' from dual union all
        select 'U 1' from dual union all
        select 'R 2' from dual union all
        select 'U 4' from dual union all
        select 'L 1' from dual union all
        select 'R 2' from dual union all
        select 'L 1' from dual union all
        select 'D 4' from dual union all
        select 'L 3' from dual union all
        select 'R 1' from dual union all
        select 'L 2' from dual union all
        select 'R 1' from dual union all
        select 'U 3' from dual union all
        select 'R 3' from dual union all
        select 'D 2' from dual union all
        select 'R 2' from dual union all
        select 'L 2' from dual union all
        select 'D 1' from dual union all
        select 'U 4' from dual union all
        select 'R 2' from dual union all
        select 'U 2' from dual union all
        select 'L 1' from dual union all
        select 'R 2' from dual union all
        select 'U 3' from dual union all
        select 'L 2' from dual union all
        select 'D 3' from dual union all
        select 'U 2' from dual union all
        select 'D 3' from dual union all
        select 'U 4' from dual union all
        select 'D 2' from dual union all
        select 'R 3' from dual union all
        select 'U 1' from dual union all
        select 'D 2' from dual union all
        select 'R 1' from dual union all
        select 'D 2' from dual union all
        select 'R 3' from dual union all
        select 'L 1' from dual union all
        select 'D 4' from dual union all
        select 'R 4' from dual union all
        select 'D 4' from dual union all
        select 'R 2' from dual union all
        select 'D 3' from dual union all
        select 'U 1' from dual union all
        select 'R 2' from dual union all
        select 'U 1' from dual union all
        select 'L 4' from dual union all
        select 'D 2' from dual union all
        select 'L 2' from dual union all
        select 'D 4' from dual union all
        select 'L 1' from dual union all
        select 'U 4' from dual union all
        select 'D 3' from dual union all
        select 'L 3' from dual union all
        select 'U 2' from dual union all
        select 'L 2' from dual union all
        select 'D 1' from dual union all
        select 'L 4' from dual union all
        select 'R 4' from dual union all
        select 'D 2' from dual union all
        select 'R 3' from dual union all
        select 'L 1' from dual union all
        select 'U 3' from dual union all
        select 'L 3' from dual union all
        select 'D 5' from dual union all
        select 'U 5' from dual union all
        select 'D 5' from dual union all
        select 'U 1' from dual union all
        select 'D 1' from dual union all
        select 'R 1' from dual union all
        select 'U 2' from dual union all
        select 'L 2' from dual union all
        select 'U 3' from dual union all
        select 'L 5' from dual union all
        select 'D 4' from dual union all
        select 'R 2' from dual union all
        select 'U 2' from dual union all
        select 'L 4' from dual union all
        select 'U 3' from dual union all
        select 'L 2' from dual union all
        select 'U 3' from dual union all
        select 'R 2' from dual union all
        select 'D 3' from dual union all
        select 'R 4' from dual union all
        select 'D 5' from dual union all
        select 'R 1' from dual union all
        select 'D 3' from dual union all
        select 'R 2' from dual union all
        select 'U 2' from dual union all
        select 'R 3' from dual union all
        select 'U 5' from dual union all
        select 'R 2' from dual union all
        select 'D 1' from dual union all
        select 'R 5' from dual union all
        select 'L 1' from dual union all
        select 'D 5' from dual union all
        select 'L 5' from dual union all
        select 'U 2' from dual union all
        select 'D 4' from dual union all
        select 'R 1' from dual union all
        select 'L 3' from dual union all
        select 'R 2' from dual union all
        select 'U 2' from dual union all
        select 'R 1' from dual union all
        select 'U 5' from dual union all
        select 'R 5' from dual union all
        select 'D 2' from dual union all
        select 'U 1' from dual union all
        select 'R 4' from dual union all
        select 'L 4' from dual union all
        select 'D 5' from dual union all
        select 'U 1' from dual union all
        select 'D 1' from dual union all
        select 'L 4' from dual union all
        select 'D 3' from dual union all
        select 'L 3' from dual union all
        select 'D 5' from dual union all
        select 'R 3' from dual union all
        select 'U 3' from dual union all
        select 'L 2' from dual union all
        select 'R 5' from dual union all
        select 'U 5' from dual union all
        select 'R 3' from dual union all
        select 'D 2' from dual union all
        select 'L 2' from dual union all
        select 'D 3' from dual union all
        select 'R 1' from dual union all
        select 'U 5' from dual union all
        select 'L 1' from dual union all
        select 'D 5' from dual union all
        select 'R 2' from dual union all
        select 'L 5' from dual union all
        select 'R 4' from dual union all
        select 'L 3' from dual union all
        select 'D 2' from dual union all
        select 'U 1' from dual union all
        select 'L 4' from dual union all
        select 'U 5' from dual union all
        select 'L 3' from dual union all
        select 'R 1' from dual union all
        select 'U 3' from dual union all
        select 'R 3' from dual union all
        select 'U 5' from dual union all
        select 'L 5' from dual union all
        select 'U 5' from dual union all
        select 'R 5' from dual union all
        select 'L 1' from dual union all
        select 'R 4' from dual union all
        select 'L 2' from dual union all
        select 'D 3' from dual union all
        select 'U 3' from dual union all
        select 'L 1' from dual union all
        select 'U 5' from dual union all
        select 'D 3' from dual union all
        select 'U 4' from dual union all
        select 'L 5' from dual union all
        select 'U 3' from dual union all
        select 'L 3' from dual union all
        select 'D 1' from dual union all
        select 'U 3' from dual union all
        select 'L 4' from dual union all
        select 'D 2' from dual union all
        select 'R 3' from dual union all
        select 'L 3' from dual union all
        select 'D 4' from dual union all
        select 'L 1' from dual union all
        select 'D 4' from dual union all
        select 'U 3' from dual union all
        select 'D 4' from dual union all
        select 'L 5' from dual union all
        select 'R 2' from dual union all
        select 'L 2' from dual union all
        select 'R 4' from dual union all
        select 'L 1' from dual union all
        select 'U 1' from dual union all
        select 'D 1' from dual union all
        select 'U 1' from dual union all
        select 'R 5' from dual union all
        select 'U 1' from dual union all
        select 'R 2' from dual union all
        select 'D 3' from dual union all
        select 'L 4' from dual union all
        select 'D 1' from dual union all
        select 'R 3' from dual union all
        select 'U 3' from dual union all
        select 'D 6' from dual union all
        select 'U 1' from dual union all
        select 'R 3' from dual union all
        select 'D 1' from dual union all
        select 'L 5' from dual union all
        select 'D 3' from dual union all
        select 'R 3' from dual union all
        select 'L 2' from dual union all
        select 'D 5' from dual union all
        select 'R 3' from dual union all
        select 'D 3' from dual union all
        select 'U 5' from dual union all
        select 'D 6' from dual union all
        select 'U 2' from dual union all
        select 'R 2' from dual union all
        select 'U 3' from dual union all
        select 'R 1' from dual union all
        select 'U 6' from dual union all
        select 'L 1' from dual union all
        select 'R 1' from dual union all
        select 'L 5' from dual union all
        select 'R 2' from dual union all
        select 'U 6' from dual union all
        select 'D 3' from dual union all
        select 'R 3' from dual union all
        select 'D 5' from dual union all
        select 'U 1' from dual union all
        select 'L 4' from dual union all
        select 'D 4' from dual union all
        select 'L 1' from dual union all
        select 'R 4' from dual union all
        select 'D 5' from dual union all
        select 'L 3' from dual union all
        select 'R 5' from dual union all
        select 'U 6' from dual union all
        select 'D 4' from dual union all
        select 'U 4' from dual union all
        select 'D 5' from dual union all
        select 'R 1' from dual union all
        select 'U 1' from dual union all
        select 'L 6' from dual union all
        select 'R 3' from dual union all
        select 'D 1' from dual union all
        select 'L 2' from dual union all
        select 'D 1' from dual union all
        select 'L 1' from dual union all
        select 'U 5' from dual union all
        select 'L 4' from dual union all
        select 'R 1' from dual union all
        select 'L 3' from dual union all
        select 'U 6' from dual union all
        select 'L 1' from dual union all
        select 'D 3' from dual union all
        select 'L 6' from dual union all
        select 'D 6' from dual union all
        select 'R 2' from dual union all
        select 'U 5' from dual union all
        select 'D 3' from dual union all
        select 'U 6' from dual union all
        select 'R 5' from dual union all
        select 'L 2' from dual union all
        select 'U 1' from dual union all
        select 'R 3' from dual union all
        select 'L 5' from dual union all
        select 'R 2' from dual union all
        select 'L 6' from dual union all
        select 'R 1' from dual union all
        select 'U 1' from dual union all
        select 'R 1' from dual union all
        select 'D 3' from dual union all
        select 'R 1' from dual union all
        select 'D 1' from dual union all
        select 'L 4' from dual union all
        select 'D 2' from dual union all
        select 'R 3' from dual union all
        select 'U 2' from dual union all
        select 'L 6' from dual union all
        select 'U 5' from dual union all
        select 'R 3' from dual union all
        select 'D 4' from dual union all
        select 'R 4' from dual union all
        select 'D 6' from dual union all
        select 'R 1' from dual union all
        select 'D 5' from dual union all
        select 'L 5' from dual union all
        select 'R 1' from dual union all
        select 'D 1' from dual union all
        select 'L 3' from dual union all
        select 'D 6' from dual union all
        select 'R 3' from dual union all
        select 'U 4' from dual union all
        select 'D 6' from dual union all
        select 'R 2' from dual union all
        select 'L 6' from dual union all
        select 'D 2' from dual union all
        select 'L 1' from dual union all
        select 'D 6' from dual union all
        select 'L 3' from dual union all
        select 'R 2' from dual union all
        select 'U 3' from dual union all
        select 'L 4' from dual union all
        select 'R 6' from dual union all
        select 'U 6' from dual union all
        select 'R 1' from dual union all
        select 'U 6' from dual union all
        select 'D 5' from dual union all
        select 'U 1' from dual union all
        select 'L 6' from dual union all
        select 'R 6' from dual union all
        select 'D 1' from dual union all
        select 'R 5' from dual union all
        select 'L 1' from dual union all
        select 'D 5' from dual union all
        select 'R 6' from dual union all
        select 'U 1' from dual union all
        select 'L 5' from dual union all
        select 'D 3' from dual union all
        select 'R 6' from dual union all
        select 'U 1' from dual union all
        select 'L 3' from dual union all
        select 'U 1' from dual union all
        select 'R 4' from dual union all
        select 'D 1' from dual union all
        select 'R 2' from dual union all
        select 'D 7' from dual union all
        select 'U 5' from dual union all
        select 'D 2' from dual union all
        select 'U 6' from dual union all
        select 'D 3' from dual union all
        select 'U 1' from dual union all
        select 'D 3' from dual union all
        select 'R 4' from dual union all
        select 'D 6' from dual union all
        select 'R 3' from dual union all
        select 'L 1' from dual union all
        select 'U 1' from dual union all
        select 'L 2' from dual union all
        select 'R 4' from dual union all
        select 'U 3' from dual union all
        select 'L 3' from dual union all
        select 'R 1' from dual union all
        select 'D 7' from dual union all
        select 'L 4' from dual union all
        select 'D 2' from dual union all
        select 'R 3' from dual union all
        select 'L 2' from dual union all
        select 'U 2' from dual union all
        select 'L 1' from dual union all
        select 'D 5' from dual union all
        select 'U 4' from dual union all
        select 'L 4' from dual union all
        select 'D 7' from dual union all
        select 'U 4' from dual union all
        select 'D 5' from dual union all
        select 'L 7' from dual union all
        select 'U 6' from dual union all
        select 'L 1' from dual union all
        select 'U 1' from dual union all
        select 'L 1' from dual union all
        select 'R 6' from dual union all
        select 'U 1' from dual union all
        select 'D 5' from dual union all
        select 'R 2' from dual union all
        select 'D 4' from dual union all
        select 'R 3' from dual union all
        select 'D 2' from dual union all
        select 'R 2' from dual union all
        select 'L 5' from dual union all
        select 'U 5' from dual union all
        select 'R 7' from dual union all
        select 'D 6' from dual union all
        select 'R 1' from dual union all
        select 'D 5' from dual union all
        select 'R 1' from dual union all
        select 'L 7' from dual union all
        select 'D 7' from dual union all
        select 'L 6' from dual union all
        select 'D 6' from dual union all
        select 'U 4' from dual union all
        select 'R 3' from dual union all
        select 'U 2' from dual union all
        select 'R 6' from dual union all
        select 'D 4' from dual union all
        select 'R 6' from dual union all
        select 'D 3' from dual union all
        select 'L 5' from dual union all
        select 'U 7' from dual union all
        select 'D 2' from dual union all
        select 'R 5' from dual union all
        select 'D 5' from dual union all
        select 'L 1' from dual union all
        select 'R 1' from dual union all
        select 'D 6' from dual union all
        select 'L 3' from dual union all
        select 'R 3' from dual union all
        select 'L 1' from dual union all
        select 'R 2' from dual union all
        select 'D 5' from dual union all
        select 'R 2' from dual union all
        select 'D 1' from dual union all
        select 'L 6' from dual union all
        select 'D 1' from dual union all
        select 'U 7' from dual union all
        select 'R 6' from dual union all
        select 'D 4' from dual union all
        select 'U 2' from dual union all
        select 'R 5' from dual union all
        select 'L 7' from dual union all
        select 'R 7' from dual union all
        select 'D 3' from dual union all
        select 'L 2' from dual union all
        select 'R 7' from dual union all
        select 'D 1' from dual union all
        select 'R 8' from dual union all
        select 'D 2' from dual union all
        select 'R 3' from dual union all
        select 'L 2' from dual union all
        select 'R 8' from dual union all
        select 'U 7' from dual union all
        select 'L 8' from dual union all
        select 'D 3' from dual union all
        select 'U 6' from dual union all
        select 'D 3' from dual union all
        select 'R 8' from dual union all
        select 'U 4' from dual union all
        select 'L 3' from dual union all
        select 'R 4' from dual union all
        select 'D 5' from dual union all
        select 'U 6' from dual union all
        select 'R 8' from dual union all
        select 'D 5' from dual union all
        select 'U 4' from dual union all
        select 'L 5' from dual union all
        select 'D 2' from dual union all
        select 'U 8' from dual union all
        select 'D 6' from dual union all
        select 'U 4' from dual union all
        select 'L 1' from dual union all
        select 'R 2' from dual union all
        select 'D 4' from dual union all
        select 'U 3' from dual union all
        select 'L 1' from dual union all
        select 'U 6' from dual union all
        select 'R 6' from dual union all
        select 'U 3' from dual union all
        select 'L 7' from dual union all
        select 'U 6' from dual union all
        select 'R 3' from dual union all
        select 'U 5' from dual union all
        select 'R 6' from dual union all
        select 'D 8' from dual union all
        select 'R 6' from dual union all
        select 'U 1' from dual union all
        select 'R 8' from dual union all
        select 'L 5' from dual union all
        select 'R 5' from dual union all
        select 'L 3' from dual union all
        select 'R 5' from dual union all
        select 'L 7' from dual union all
        select 'R 3' from dual union all
        select 'D 6' from dual union all
        select 'R 1' from dual union all
        select 'D 4' from dual union all
        select 'R 5' from dual union all
        select 'U 6' from dual union all
        select 'R 4' from dual union all
        select 'D 3' from dual union all
        select 'R 4' from dual union all
        select 'D 7' from dual union all
        select 'R 5' from dual union all
        select 'U 5' from dual union all
        select 'D 2' from dual union all
        select 'R 6' from dual union all
        select 'U 3' from dual union all
        select 'L 1' from dual union all
        select 'U 4' from dual union all
        select 'R 7' from dual union all
        select 'U 5' from dual union all
        select 'D 2' from dual union all
        select 'R 3' from dual union all
        select 'L 1' from dual union all
        select 'U 2' from dual union all
        select 'R 1' from dual union all
        select 'D 7' from dual union all
        select 'L 4' from dual union all
        select 'R 4' from dual union all
        select 'D 2' from dual union all
        select 'U 8' from dual union all
        select 'D 2' from dual union all
        select 'L 4' from dual union all
        select 'D 7' from dual union all
        select 'R 6' from dual union all
        select 'U 8' from dual union all
        select 'R 7' from dual union all
        select 'D 1' from dual union all
        select 'U 4' from dual union all
        select 'L 8' from dual union all
        select 'D 8' from dual union all
        select 'R 5' from dual union all
        select 'D 2' from dual union all
        select 'L 5' from dual union all
        select 'D 1' from dual union all
        select 'L 1' from dual union all
        select 'U 4' from dual union all
        select 'D 4' from dual union all
        select 'L 7' from dual union all
        select 'D 3' from dual union all
        select 'L 8' from dual union all
        select 'D 1' from dual union all
        select 'R 1' from dual union all
        select 'L 2' from dual union all
        select 'U 7' from dual union all
        select 'R 8' from dual union all
        select 'D 3' from dual union all
        select 'R 7' from dual union all
        select 'D 1' from dual union all
        select 'R 2' from dual union all
        select 'U 8' from dual union all
        select 'R 8' from dual union all
        select 'U 2' from dual union all
        select 'D 6' from dual union all
        select 'U 7' from dual union all
        select 'R 1' from dual union all
        select 'U 8' from dual union all
        select 'R 5' from dual union all
        select 'D 3' from dual union all
        select 'R 4' from dual union all
        select 'L 2' from dual union all
        select 'D 1' from dual union all
        select 'L 6' from dual union all
        select 'D 8' from dual union all
        select 'R 1' from dual union all
        select 'L 4' from dual union all
        select 'U 5' from dual union all
        select 'L 7' from dual union all
        select 'D 5' from dual union all
        select 'U 4' from dual union all
        select 'L 4' from dual union all
        select 'R 9' from dual union all
        select 'L 9' from dual union all
        select 'U 7' from dual union all
        select 'L 3' from dual union all
        select 'R 4' from dual union all
        select 'U 2' from dual union all
        select 'R 5' from dual union all
        select 'D 1' from dual union all
        select 'L 5' from dual union all
        select 'R 7' from dual union all
        select 'D 7' from dual union all
        select 'L 6' from dual union all
        select 'U 2' from dual union all
        select 'L 6' from dual union all
        select 'R 5' from dual union all
        select 'D 2' from dual union all
        select 'U 6' from dual union all
        select 'R 3' from dual union all
        select 'U 7' from dual union all
        select 'D 8' from dual union all
        select 'U 3' from dual union all
        select 'L 3' from dual union all
        select 'U 5' from dual union all
        select 'D 5' from dual union all
        select 'U 1' from dual union all
        select 'D 6' from dual union all
        select 'R 4' from dual union all
        select 'U 3' from dual union all
        select 'R 4' from dual union all
        select 'U 1' from dual union all
        select 'D 3' from dual union all
        select 'R 2' from dual union all
        select 'L 8' from dual union all
        select 'D 6' from dual union all
        select 'L 3' from dual union all
        select 'U 7' from dual union all
        select 'D 2' from dual union all
        select 'R 9' from dual union all
        select 'D 4' from dual union all
        select 'L 5' from dual union all
        select 'R 4' from dual union all
        select 'L 8' from dual union all
        select 'D 7' from dual union all
        select 'R 2' from dual union all
        select 'D 3' from dual union all
        select 'U 5' from dual union all
        select 'D 6' from dual union all
        select 'R 1' from dual union all
        select 'L 1' from dual union all
        select 'D 5' from dual union all
        select 'L 6' from dual union all
        select 'U 4' from dual union all
        select 'D 2' from dual union all
        select 'R 5' from dual union all
        select 'U 2' from dual union all
        select 'R 4' from dual union all
        select 'U 5' from dual union all
        select 'D 7' from dual union all
        select 'R 8' from dual union all
        select 'D 2' from dual union all
        select 'R 6' from dual union all
        select 'D 4' from dual union all
        select 'R 6' from dual union all
        select 'L 8' from dual union all
        select 'U 4' from dual union all
        select 'L 3' from dual union all
        select 'U 4' from dual union all
        select 'L 3' from dual union all
        select 'R 6' from dual union all
        select 'D 4' from dual union all
        select 'L 5' from dual union all
        select 'D 1' from dual union all
        select 'U 8' from dual union all
        select 'L 8' from dual union all
        select 'U 2' from dual union all
        select 'L 9' from dual union all
        select 'R 6' from dual union all
        select 'L 1' from dual union all
        select 'D 5' from dual union all
        select 'L 5' from dual union all
        select 'R 4' from dual union all
        select 'D 3' from dual union all
        select 'R 4' from dual union all
        select 'L 8' from dual union all
        select 'R 9' from dual union all
        select 'D 2' from dual union all
        select 'R 8' from dual union all
        select 'D 6' from dual union all
        select 'L 4' from dual union all
        select 'D 2' from dual union all
        select 'U 3' from dual union all
        select 'R 9' from dual union all
        select 'L 7' from dual union all
        select 'D 9' from dual union all
        select 'R 8' from dual union all
        select 'U 3' from dual union all
        select 'L 10' from dual union all
        select 'D 10' from dual union all
        select 'L 7' from dual union all
        select 'R 8' from dual union all
        select 'L 7' from dual union all
        select 'D 7' from dual union all
        select 'L 7' from dual union all
        select 'D 6' from dual union all
        select 'R 1' from dual union all
        select 'U 10' from dual union all
        select 'R 7' from dual union all
        select 'U 10' from dual union all
        select 'L 1' from dual union all
        select 'D 7' from dual union all
        select 'L 2' from dual union all
        select 'D 1' from dual union all
        select 'U 10' from dual union all
        select 'D 5' from dual union all
        select 'L 1' from dual union all
        select 'U 9' from dual union all
        select 'L 10' from dual union all
        select 'U 6' from dual union all
        select 'L 4' from dual union all
        select 'U 10' from dual union all
        select 'R 7' from dual union all
        select 'L 10' from dual union all
        select 'U 8' from dual union all
        select 'D 6' from dual union all
        select 'L 4' from dual union all
        select 'D 9' from dual union all
        select 'L 7' from dual union all
        select 'R 5' from dual union all
        select 'D 3' from dual union all
        select 'L 2' from dual union all
        select 'R 9' from dual union all
        select 'U 4' from dual union all
        select 'D 2' from dual union all
        select 'L 6' from dual union all
        select 'R 4' from dual union all
        select 'L 3' from dual union all
        select 'R 1' from dual union all
        select 'L 2' from dual union all
        select 'U 8' from dual union all
        select 'L 7' from dual union all
        select 'U 4' from dual union all
        select 'D 8' from dual union all
        select 'R 9' from dual union all
        select 'L 4' from dual union all
        select 'R 1' from dual union all
        select 'U 6' from dual union all
        select 'L 5' from dual union all
        select 'R 10' from dual union all
        select 'D 10' from dual union all
        select 'U 2' from dual union all
        select 'R 8' from dual union all
        select 'U 1' from dual union all
        select 'R 4' from dual union all
        select 'D 10' from dual union all
        select 'R 2' from dual union all
        select 'L 2' from dual union all
        select 'D 3' from dual union all
        select 'U 8' from dual union all
        select 'L 7' from dual union all
        select 'D 9' from dual union all
        select 'L 8' from dual union all
        select 'D 7' from dual union all
        select 'R 9' from dual union all
        select 'L 6' from dual union all
        select 'U 8' from dual union all
        select 'D 7' from dual union all
        select 'U 6' from dual union all
        select 'D 5' from dual union all
        select 'R 3' from dual union all
        select 'L 7' from dual union all
        select 'U 4' from dual union all
        select 'R 7' from dual union all
        select 'D 9' from dual union all
        select 'R 9' from dual union all
        select 'D 5' from dual union all
        select 'L 6' from dual union all
        select 'U 2' from dual union all
        select 'R 7' from dual union all
        select 'U 7' from dual union all
        select 'D 3' from dual union all
        select 'R 10' from dual union all
        select 'L 10' from dual union all
        select 'R 1' from dual union all
        select 'D 10' from dual union all
        select 'U 2' from dual union all
        select 'R 3' from dual union all
        select 'U 2' from dual union all
        select 'L 4' from dual union all
        select 'R 5' from dual union all
        select 'L 1' from dual union all
        select 'U 6' from dual union all
        select 'R 1' from dual union all
        select 'U 6' from dual union all
        select 'R 10' from dual union all
        select 'L 2' from dual union all
        select 'D 8' from dual union all
        select 'U 3' from dual union all
        select 'L 8' from dual union all
        select 'U 4' from dual union all
        select 'L 8' from dual union all
        select 'U 10' from dual union all
        select 'D 7' from dual union all
        select 'R 4' from dual union all
        select 'U 10' from dual union all
        select 'L 3' from dual union all
        select 'D 7' from dual union all
        select 'L 1' from dual union all
        select 'R 5' from dual union all
        select 'L 1' from dual union all
        select 'U 5' from dual union all
        select 'L 1' from dual union all
        select 'D 1' from dual union all
        select 'R 7' from dual union all
        select 'D 3' from dual union all
        select 'L 3' from dual union all
        select 'R 2' from dual union all
        select 'U 7' from dual union all
        select 'L 11' from dual union all
        select 'R 5' from dual union all
        select 'D 8' from dual union all
        select 'R 1' from dual union all
        select 'U 3' from dual union all
        select 'R 1' from dual union all
        select 'L 11' from dual union all
        select 'R 4' from dual union all
        select 'U 1' from dual union all
        select 'D 9' from dual union all
        select 'R 7' from dual union all
        select 'D 8' from dual union all
        select 'R 11' from dual union all
        select 'D 3' from dual union all
        select 'U 1' from dual union all
        select 'L 7' from dual union all
        select 'R 5' from dual union all
        select 'L 5' from dual union all
        select 'R 1' from dual union all
        select 'D 4' from dual union all
        select 'R 6' from dual union all
        select 'D 8' from dual union all
        select 'R 3' from dual union all
        select 'L 10' from dual union all
        select 'R 10' from dual union all
        select 'D 4' from dual union all
        select 'L 7' from dual union all
        select 'R 7' from dual union all
        select 'L 9' from dual union all
        select 'D 11' from dual union all
        select 'L 1' from dual union all
        select 'D 1' from dual union all
        select 'L 10' from dual union all
        select 'U 6' from dual union all
        select 'L 8' from dual union all
        select 'R 11' from dual union all
        select 'D 10' from dual union all
        select 'L 4' from dual union all
        select 'U 5' from dual union all
        select 'D 8' from dual union all
        select 'R 8' from dual union all
        select 'L 3' from dual union all
        select 'U 4' from dual union all
        select 'R 4' from dual union all
        select 'U 7' from dual union all
        select 'R 7' from dual union all
        select 'D 8' from dual union all
        select 'U 6' from dual union all
        select 'R 11' from dual union all
        select 'L 8' from dual union all
        select 'D 10' from dual union all
        select 'R 7' from dual union all
        select 'D 8' from dual union all
        select 'L 11' from dual union all
        select 'U 3' from dual union all
        select 'D 7' from dual union all
        select 'U 2' from dual union all
        select 'R 5' from dual union all
        select 'L 6' from dual union all
        select 'U 10' from dual union all
        select 'R 4' from dual union all
        select 'L 9' from dual union all
        select 'U 7' from dual union all
        select 'D 7' from dual union all
        select 'R 7' from dual union all
        select 'D 6' from dual union all
        select 'R 10' from dual union all
        select 'U 4' from dual union all
        select 'L 3' from dual union all
        select 'D 4' from dual union all
        select 'R 8' from dual union all
        select 'L 4' from dual union all
        select 'R 3' from dual union all
        select 'U 2' from dual union all
        select 'R 4' from dual union all
        select 'U 2' from dual union all
        select 'L 6' from dual union all
        select 'D 5' from dual union all
        select 'R 3' from dual union all
        select 'D 1' from dual union all
        select 'U 4' from dual union all
        select 'L 6' from dual union all
        select 'U 10' from dual union all
        select 'D 9' from dual union all
        select 'L 6' from dual union all
        select 'U 4' from dual union all
        select 'R 3' from dual union all
        select 'L 2' from dual union all
        select 'D 4' from dual union all
        select 'R 1' from dual union all
        select 'L 3' from dual union all
        select 'R 4' from dual union all
        select 'L 2' from dual union all
        select 'R 7' from dual union all
        select 'L 6' from dual union all
        select 'R 7' from dual union all
        select 'U 8' from dual union all
        select 'D 6' from dual union all
        select 'U 2' from dual union all
        select 'L 11' from dual union all
        select 'R 9' from dual union all
        select 'L 10' from dual union all
        select 'R 6' from dual union all
        select 'D 4' from dual union all
        select 'R 7' from dual union all
        select 'L 6' from dual union all
        select 'D 2' from dual union all
        select 'L 10' from dual union all
        select 'D 3' from dual union all
        select 'L 2' from dual union all
        select 'D 9' from dual union all
        select 'L 2' from dual union all
        select 'R 10' from dual union all
        select 'L 8' from dual union all
        select 'U 2' from dual union all
        select 'L 9' from dual union all
        select 'D 12' from dual union all
        select 'U 3' from dual union all
        select 'R 7' from dual union all
        select 'U 6' from dual union all
        select 'L 1' from dual union all
        select 'R 6' from dual union all
        select 'D 9' from dual union all
        select 'U 1' from dual union all
        select 'R 9' from dual union all
        select 'U 5' from dual union all
        select 'L 5' from dual union all
        select 'R 12' from dual union all
        select 'L 5' from dual union all
        select 'U 4' from dual union all
        select 'R 1' from dual union all
        select 'D 1' from dual union all
        select 'R 7' from dual union all
        select 'L 1' from dual union all
        select 'R 1' from dual union all
        select 'D 3' from dual union all
        select 'U 5' from dual union all
        select 'R 9' from dual union all
        select 'D 6' from dual union all
        select 'L 12' from dual union all
        select 'R 2' from dual union all
        select 'U 4' from dual union all
        select 'R 2' from dual union all
        select 'U 2' from dual union all
        select 'R 11' from dual union all
        select 'U 2' from dual union all
        select 'D 3' from dual union all
        select 'U 2' from dual union all
        select 'L 11' from dual union all
        select 'D 11' from dual union all
        select 'R 1' from dual union all
        select 'D 10' from dual union all
        select 'L 5' from dual union all
        select 'D 11' from dual union all
        select 'R 4' from dual union all
        select 'D 4' from dual union all
        select 'R 12' from dual union all
        select 'U 11' from dual union all
        select 'R 2' from dual union all
        select 'U 1' from dual union all
        select 'D 11' from dual union all
        select 'L 3' from dual union all
        select 'D 3' from dual union all
        select 'R 5' from dual union all
        select 'D 6' from dual union all
        select 'R 9' from dual union all
        select 'U 10' from dual union all
        select 'L 9' from dual union all
        select 'D 4' from dual union all
        select 'U 8' from dual union all
        select 'D 5' from dual union all
        select 'R 5' from dual union all
        select 'U 1' from dual union all
        select 'R 2' from dual union all
        select 'U 12' from dual union all
        select 'L 2' from dual union all
        select 'R 9' from dual union all
        select 'D 5' from dual union all
        select 'U 11' from dual union all
        select 'D 8' from dual union all
        select 'R 8' from dual union all
        select 'L 10' from dual union all
        select 'D 10' from dual union all
        select 'U 9' from dual union all
        select 'L 5' from dual union all
        select 'U 2' from dual union all
        select 'R 4' from dual union all
        select 'D 4' from dual union all
        select 'U 11' from dual union all
        select 'R 2' from dual union all
        select 'U 8' from dual union all
        select 'R 5' from dual union all
        select 'U 3' from dual union all
        select 'D 12' from dual union all
        select 'L 10' from dual union all
        select 'U 11' from dual union all
        select 'D 12' from dual union all
        select 'R 3' from dual union all
        select 'L 6' from dual union all
        select 'R 5' from dual union all
        select 'U 6' from dual union all
        select 'R 9' from dual union all
        select 'U 7' from dual union all
        select 'R 9' from dual union all
        select 'D 6' from dual union all
        select 'L 3' from dual union all
        select 'U 3' from dual union all
        select 'L 5' from dual union all
        select 'D 1' from dual union all
        select 'L 9' from dual union all
        select 'U 9' from dual union all
        select 'R 2' from dual union all
        select 'D 9' from dual union all
        select 'R 5' from dual union all
        select 'U 9' from dual union all
        select 'R 7' from dual union all
        select 'D 5' from dual union all
        select 'R 10' from dual union all
        select 'D 7' from dual union all
        select 'U 4' from dual union all
        select 'L 1' from dual union all
        select 'D 6' from dual union all
        select 'U 10' from dual union all
        select 'L 12' from dual union all
        select 'R 7' from dual union all
        select 'U 9' from dual union all
        select 'L 1' from dual union all
        select 'D 5' from dual union all
        select 'U 8' from dual union all
        select 'D 3' from dual union all
        select 'L 6' from dual union all
        select 'D 7' from dual union all
        select 'R 7' from dual union all
        select 'L 13' from dual union all
        select 'D 4' from dual union all
        select 'R 3' from dual union all
        select 'D 8' from dual union all
        select 'L 10' from dual union all
        select 'R 11' from dual union all
        select 'D 2' from dual union all
        select 'R 8' from dual union all
        select 'D 7' from dual union all
        select 'R 8' from dual union all
        select 'L 13' from dual union all
        select 'D 3' from dual union all
        select 'L 2' from dual union all
        select 'D 4' from dual union all
        select 'L 2' from dual union all
        select 'U 5' from dual union all
        select 'R 6' from dual union all
        select 'U 9' from dual union all
        select 'R 7' from dual union all
        select 'L 3' from dual union all
        select 'R 13' from dual union all
        select 'L 11' from dual union all
        select 'R 1' from dual union all
        select 'D 13' from dual union all
        select 'L 10' from dual union all
        select 'D 6' from dual union all
        select 'R 2' from dual union all
        select 'L 12' from dual union all
        select 'D 8' from dual union all
        select 'U 12' from dual union all
        select 'D 5' from dual union all
        select 'R 3' from dual union all
        select 'U 5' from dual union all
        select 'D 6' from dual union all
        select 'U 4' from dual union all
        select 'D 6' from dual union all
        select 'U 7' from dual union all
        select 'D 12' from dual union all
        select 'R 6' from dual union all
        select 'L 1' from dual union all
        select 'U 3' from dual union all
        select 'R 10' from dual union all
        select 'U 7' from dual union all
        select 'L 12' from dual union all
        select 'R 11' from dual union all
        select 'D 1' from dual union all
        select 'L 9' from dual union all
        select 'U 12' from dual union all
        select 'L 5' from dual union all
        select 'D 6' from dual union all
        select 'U 7' from dual union all
        select 'D 11' from dual union all
        select 'L 9' from dual union all
        select 'D 13' from dual union all
        select 'L 7' from dual union all
        select 'D 13' from dual union all
        select 'U 5' from dual union all
        select 'R 9' from dual union all
        select 'U 8' from dual union all
        select 'R 9' from dual union all
        select 'D 9' from dual union all
        select 'L 9' from dual union all
        select 'R 3' from dual union all
        select 'D 11' from dual union all
        select 'U 7' from dual union all
        select 'L 9' from dual union all
        select 'U 6' from dual union all
        select 'L 11' from dual union all
        select 'U 2' from dual union all
        select 'R 6' from dual union all
        select 'U 6' from dual union all
        select 'R 12' from dual union all
        select 'U 1' from dual union all
        select 'L 3' from dual union all
        select 'U 5' from dual union all
        select 'R 9' from dual union all
        select 'U 11' from dual union all
        select 'R 13' from dual union all
        select 'U 11' from dual union all
        select 'D 13' from dual union all
        select 'R 7' from dual union all
        select 'U 11' from dual union all
        select 'L 9' from dual union all
        select 'D 10' from dual union all
        select 'U 1' from dual union all
        select 'L 12' from dual union all
        select 'R 13' from dual union all
        select 'D 3' from dual union all
        select 'U 4' from dual union all
        select 'L 11' from dual union all
        select 'U 3' from dual union all
        select 'D 2' from dual union all
        select 'R 10' from dual union all
        select 'U 9' from dual union all
        select 'D 4' from dual union all
        select 'L 14' from dual union all
        select 'R 2' from dual union all
        select 'D 2' from dual union all
        select 'U 13' from dual union all
        select 'D 3' from dual union all
        select 'U 10' from dual union all
        select 'L 7' from dual union all
        select 'U 6' from dual union all
        select 'D 13' from dual union all
        select 'U 9' from dual union all
        select 'R 1' from dual union all
        select 'D 1' from dual union all
        select 'R 1' from dual union all
        select 'D 5' from dual union all
        select 'L 2' from dual union all
        select 'D 7' from dual union all
        select 'U 10' from dual union all
        select 'R 1' from dual union all
        select 'D 8' from dual union all
        select 'L 13' from dual union all
        select 'R 2' from dual union all
        select 'U 10' from dual union all
        select 'L 6' from dual union all
        select 'D 8' from dual union all
        select 'R 7' from dual union all
        select 'U 9' from dual union all
        select 'D 4' from dual union all
        select 'U 7' from dual union all
        select 'D 6' from dual union all
        select 'R 12' from dual union all
        select 'U 1' from dual union all
        select 'D 13' from dual union all
        select 'U 4' from dual union all
        select 'L 13' from dual union all
        select 'D 7' from dual union all
        select 'R 5' from dual union all
        select 'U 10' from dual union all
        select 'D 12' from dual union all
        select 'U 5' from dual union all
        select 'L 1' from dual union all
        select 'U 12' from dual union all
        select 'D 4' from dual union all
        select 'U 3' from dual union all
        select 'R 3' from dual union all
        select 'D 9' from dual union all
        select 'L 5' from dual union all
        select 'R 2' from dual union all
        select 'D 3' from dual union all
        select 'U 6' from dual union all
        select 'R 14' from dual union all
        select 'L 2' from dual union all
        select 'R 3' from dual union all
        select 'U 11' from dual union all
        select 'R 9' from dual union all
        select 'L 13' from dual union all
        select 'D 1' from dual union all
        select 'U 8' from dual union all
        select 'D 2' from dual union all
        select 'R 12' from dual union all
        select 'D 5' from dual union all
        select 'L 6' from dual union all
        select 'U 14' from dual union all
        select 'R 1' from dual union all
        select 'D 2' from dual union all
        select 'L 6' from dual union all
        select 'R 7' from dual union all
        select 'L 8' from dual union all
        select 'D 6' from dual union all
        select 'U 7' from dual union all
        select 'L 2' from dual union all
        select 'R 2' from dual union all
        select 'D 5' from dual union all
        select 'R 6' from dual union all
        select 'U 1' from dual union all
        select 'D 8' from dual union all
        select 'L 12' from dual union all
        select 'D 7' from dual union all
        select 'L 6' from dual union all
        select 'D 8' from dual union all
        select 'L 4' from dual union all
        select 'U 4' from dual union all
        select 'D 13' from dual union all
        select 'R 11' from dual union all
        select 'D 1' from dual union all
        select 'R 9' from dual union all
        select 'L 6' from dual union all
        select 'D 8' from dual union all
        select 'L 12' from dual union all
        select 'U 11' from dual union all
        select 'D 11' from dual union all
        select 'U 4' from dual union all
        select 'D 12' from dual union all
        select 'R 4' from dual union all
        select 'L 14' from dual union all
        select 'U 6' from dual union all
        select 'D 3' from dual union all
        select 'R 8' from dual union all
        select 'D 7' from dual union all
        select 'L 12' from dual union all
        select 'U 12' from dual union all
        select 'R 10' from dual union all
        select 'U 2' from dual union all
        select 'R 6' from dual union all
        select 'L 1' from dual union all
        select 'R 11' from dual union all
        select 'U 2' from dual union all
        select 'L 4' from dual union all
        select 'U 12' from dual union all
        select 'R 5' from dual union all
        select 'U 8' from dual union all
        select 'L 15' from dual union all
        select 'R 5' from dual union all
        select 'U 4' from dual union all
        select 'R 9' from dual union all
        select 'D 8' from dual union all
        select 'U 15' from dual union all
        select 'D 10' from dual union all
        select 'R 10' from dual union all
        select 'L 9' from dual union all
        select 'R 12' from dual union all
        select 'L 8' from dual union all
        select 'D 14' from dual union all
        select 'R 2' from dual union all
        select 'D 11' from dual union all
        select 'L 14' from dual union all
        select 'D 8' from dual union all
        select 'L 1' from dual union all
        select 'D 15' from dual union all
        select 'U 4' from dual union all
        select 'L 4' from dual union all
        select 'D 9' from dual union all
        select 'R 4' from dual union all
        select 'D 10' from dual union all
        select 'L 1' from dual union all
        select 'U 7' from dual union all
        select 'D 13' from dual union all
        select 'R 15' from dual union all
        select 'U 12' from dual union all
        select 'R 11' from dual union all
        select 'D 12' from dual union all
        select 'R 2' from dual union all
        select 'L 7' from dual union all
        select 'D 15' from dual union all
        select 'L 1' from dual union all
        select 'U 4' from dual union all
        select 'D 14' from dual union all
        select 'L 7' from dual union all
        select 'D 1' from dual union all
        select 'R 9' from dual union all
        select 'U 1' from dual union all
        select 'L 3' from dual union all
        select 'D 2' from dual union all
        select 'L 5' from dual union all
        select 'D 13' from dual union all
        select 'R 3' from dual union all
        select 'L 12' from dual union all
        select 'U 5' from dual union all
        select 'L 13' from dual union all
        select 'U 5' from dual union all
        select 'L 2' from dual union all
        select 'D 9' from dual union all
        select 'L 1' from dual union all
        select 'D 10' from dual union all
        select 'L 14' from dual union all
        select 'D 14' from dual union all
        select 'U 5' from dual union all
        select 'D 14' from dual union all
        select 'U 5' from dual union all
        select 'D 4' from dual union all
        select 'R 12' from dual union all
        select 'U 10' from dual union all
        select 'R 14' from dual union all
        select 'D 1' from dual union all
        select 'L 1' from dual union all
        select 'U 8' from dual union all
        select 'D 7' from dual union all
        select 'L 13' from dual union all
        select 'R 5' from dual union all
        select 'L 7' from dual union all
        select 'D 5' from dual union all
        select 'L 3' from dual union all
        select 'U 15' from dual union all
        select 'R 8' from dual union all
        select 'L 9' from dual union all
        select 'D 14' from dual union all
        select 'R 14' from dual union all
        select 'L 12' from dual union all
        select 'D 7' from dual union all
        select 'L 15' from dual union all
        select 'D 14' from dual union all
        select 'U 12' from dual union all
        select 'L 7' from dual union all
        select 'R 11' from dual union all
        select 'L 10' from dual union all
        select 'D 8' from dual union all
        select 'L 7' from dual union all
        select 'R 14' from dual union all
        select 'L 11' from dual union all
        select 'U 1' from dual union all
        select 'R 9' from dual union all
        select 'U 13' from dual union all
        select 'R 14' from dual union all
        select 'D 6' from dual union all
        select 'U 1' from dual union all
        select 'L 4' from dual union all
        select 'R 12' from dual union all
        select 'L 2' from dual union all
        select 'U 12' from dual union all
        select 'L 12' from dual union all
        select 'D 13' from dual union all
        select 'U 13' from dual union all
        select 'R 12' from dual union all
        select 'U 5' from dual union all
        select 'R 9' from dual union all
        select 'U 4' from dual union all
        select 'D 13' from dual union all
        select 'L 7' from dual union all
        select 'D 4' from dual union all
        select 'U 16' from dual union all
        select 'D 11' from dual union all
        select 'U 16' from dual union all
        select 'R 12' from dual union all
        select 'U 10' from dual union all
        select 'R 14' from dual union all
        select 'L 1' from dual union all
        select 'U 12' from dual union all
        select 'R 4' from dual union all
        select 'U 7' from dual union all
        select 'R 10' from dual union all
        select 'D 14' from dual union all
        select 'R 9' from dual union all
        select 'D 9' from dual union all
        select 'L 8' from dual union all
        select 'R 11' from dual union all
        select 'L 7' from dual union all
        select 'U 5' from dual union all
        select 'R 15' from dual union all
        select 'U 1' from dual union all
        select 'D 12' from dual union all
        select 'U 5' from dual union all
        select 'D 11' from dual union all
        select 'U 5' from dual union all
        select 'D 11' from dual union all
        select 'L 13' from dual union all
        select 'R 6' from dual union all
        select 'D 10' from dual union all
        select 'U 1' from dual union all
        select 'L 5' from dual union all
        select 'U 11' from dual union all
        select 'L 4' from dual union all
        select 'U 14' from dual union all
        select 'L 15' from dual union all
        select 'R 14' from dual union all
        select 'L 4' from dual union all
        select 'D 13' from dual union all
        select 'L 11' from dual union all
        select 'D 1' from dual union all
        select 'U 12' from dual union all
        select 'D 2' from dual union all
        select 'L 13' from dual union all
        select 'D 10' from dual union all
        select 'L 8' from dual union all
        select 'U 15' from dual union all
        select 'R 3' from dual union all
        select 'U 5' from dual union all
        select 'R 13' from dual union all
        select 'L 11' from dual union all
        select 'U 12' from dual union all
        select 'L 14' from dual union all
        select 'R 10' from dual union all
        select 'D 15' from dual union all
        select 'R 2' from dual union all
        select 'U 6' from dual union all
        select 'D 15' from dual union all
        select 'U 11' from dual union all
        select 'D 9' from dual union all
        select 'U 10' from dual union all
        select 'R 16' from dual union all
        select 'U 16' from dual union all
        select 'D 6' from dual union all
        select 'R 2' from dual union all
        select 'L 4' from dual union all
        select 'D 15' from dual union all
        select 'L 8' from dual union all
        select 'U 8' from dual union all
        select 'L 14' from dual union all
        select 'D 8' from dual union all
        select 'U 4' from dual union all
        select 'R 2' from dual union all
        select 'D 4' from dual union all
        select 'U 11' from dual union all
        select 'R 9' from dual union all
        select 'L 15' from dual union all
        select 'U 5' from dual union all
        select 'L 15' from dual union all
        select 'D 12' from dual union all
        select 'R 9' from dual union all
        select 'U 3' from dual union all
        select 'R 7' from dual union all
        select 'D 14' from dual union all
        select 'U 6' from dual union all
        select 'R 11' from dual union all
        select 'L 16' from dual union all
        select 'D 5' from dual union all
        select 'R 15' from dual union all
        select 'D 6' from dual union all
        select 'U 5' from dual union all
        select 'L 13' from dual union all
        select 'U 5' from dual union all
        select 'R 4' from dual union all
        select 'U 11' from dual union all
        select 'R 13' from dual union all
        select 'D 7' from dual union all
        select 'R 7' from dual union all
        select 'U 12' from dual union all
        select 'R 13' from dual union all
        select 'U 1' from dual union all
        select 'L 5' from dual union all
        select 'D 6' from dual union all
        select 'R 8' from dual union all
        select 'U 14' from dual union all
        select 'R 6' from dual union all
        select 'D 16' from dual union all
        select 'R 8' from dual union all
        select 'D 6' from dual union all
        select 'R 5' from dual union all
        select 'U 6' from dual union all
        select 'D 2' from dual union all
        select 'U 4' from dual union all
        select 'R 5' from dual union all
        select 'D 17' from dual union all
        select 'L 3' from dual union all
        select 'D 1' from dual union all
        select 'R 9' from dual union all
        select 'U 6' from dual union all
        select 'R 13' from dual union all
        select 'L 3' from dual union all
        select 'D 15' from dual union all
        select 'L 9' from dual union all
        select 'D 4' from dual union all
        select 'R 6' from dual union all
        select 'D 13' from dual union all
        select 'U 11' from dual union all
        select 'D 2' from dual union all
        select 'U 10' from dual union all
        select 'L 11' from dual union all
        select 'D 4' from dual union all
        select 'U 17' from dual union all
        select 'R 12' from dual union all
        select 'D 12' from dual union all
        select 'R 7' from dual union all
        select 'D 10' from dual union all
        select 'U 7' from dual union all
        select 'R 3' from dual union all
        select 'L 5' from dual union all
        select 'D 5' from dual union all
        select 'R 3' from dual union all
        select 'D 3' from dual union all
        select 'U 6' from dual union all
        select 'D 6' from dual union all
        select 'U 17' from dual union all
        select 'L 16' from dual union all
        select 'D 3' from dual union all
        select 'R 14' from dual union all
        select 'D 5' from dual union all
        select 'U 12' from dual union all
        select 'L 13' from dual union all
        select 'U 7' from dual union all
        select 'D 5' from dual union all
        select 'R 17' from dual union all
        select 'L 7' from dual union all
        select 'D 12' from dual union all
        select 'U 9' from dual union all
        select 'D 15' from dual union all
        select 'L 2' from dual union all
        select 'R 13' from dual union all
        select 'L 14' from dual union all
        select 'D 1' from dual union all
        select 'L 3' from dual union all
        select 'U 17' from dual union all
        select 'R 9' from dual union all
        select 'U 4' from dual union all
        select 'L 14' from dual union all
        select 'R 8' from dual union all
        select 'D 15' from dual union all
        select 'L 11' from dual union all
        select 'U 15' from dual union all
        select 'L 9' from dual union all
        select 'U 4' from dual union all
        select 'L 10' from dual union all
        select 'U 13' from dual union all
        select 'D 12' from dual union all
        select 'U 9' from dual union all
        select 'L 8' from dual union all
        select 'R 12' from dual union all
        select 'U 5' from dual union all
        select 'D 13' from dual union all
        select 'U 10' from dual union all
        select 'R 13' from dual union all
        select 'U 1' from dual union all
        select 'L 14' from dual union all
        select 'D 10' from dual union all
        select 'U 10' from dual union all
        select 'R 3' from dual union all
        select 'D 7' from dual union all
        select 'R 5' from dual union all
        select 'D 10' from dual union all
        select 'R 6' from dual union all
        select 'U 1' from dual union all
        select 'D 1' from dual union all
        select 'R 3' from dual union all
        select 'L 16' from dual union all
        select 'D 4' from dual union all
        select 'U 13' from dual union all
        select 'D 17' from dual union all
        select 'L 5' from dual union all
        select 'R 14' from dual union all
        select 'U 3' from dual union all
        select 'R 12' from dual union all
        select 'U 5' from dual union all
        select 'D 2' from dual union all
        select 'U 9' from dual union all
        select 'R 11' from dual union all
        select 'D 13' from dual union all
        select 'L 6' from dual union all
        select 'U 3' from dual union all
        select 'R 17' from dual union all
        select 'L 11' from dual union all
        select 'R 17' from dual union all
        select 'L 13' from dual union all
        select 'U 2' from dual union all
        select 'R 17' from dual union all
        select 'U 9' from dual union all
        select 'L 3' from dual union all
        select 'R 16' from dual union all
        select 'D 1' from dual union all
        select 'U 13' from dual union all
        select 'D 3' from dual union all
        select 'R 7' from dual union all
        select 'L 9' from dual union all
        select 'R 16' from dual union all
        select 'D 17' from dual union all
        select 'L 3' from dual union all
        select 'U 3' from dual union all
        select 'R 7' from dual union all
        select 'L 15' from dual union all
        select 'U 3' from dual union all
        select 'R 6' from dual union all
        select 'L 11' from dual union all
        select 'R 11' from dual union all
        select 'D 2' from dual union all
        select 'U 1' from dual union all
        select 'L 4' from dual union all
        select 'D 6' from dual union all
        select 'L 15' from dual union all
        select 'R 9' from dual union all
        select 'D 14' from dual union all
        select 'U 1' from dual union all
        select 'L 1' from dual union all
        select 'U 10' from dual union all
        select 'L 18' from dual union all
        select 'D 4' from dual union all
        select 'R 12' from dual union all
        select 'L 14' from dual union all
        select 'R 11' from dual union all
        select 'D 14' from dual union all
        select 'L 15' from dual union all
        select 'U 17' from dual union all
        select 'L 6' from dual union all
        select 'U 11' from dual union all
        select 'D 14' from dual union all
        select 'U 1' from dual union all
        select 'L 9' from dual union all
        select 'D 8' from dual union all
        select 'U 6' from dual union all
        select 'L 18' from dual union all
        select 'R 2' from dual union all
        select 'D 4' from dual union all
        select 'L 1' from dual union all
        select 'D 13' from dual union all
        select 'L 17' from dual union all
        select 'U 6' from dual union all
        select 'L 18' from dual union all
        select 'U 16' from dual union all
        select 'R 1' from dual union all
        select 'U 8' from dual union all
        select 'R 8' from dual union all
        select 'L 17' from dual union all
        select 'D 13' from dual union all
        select 'U 18' from dual union all
        select 'R 5' from dual union all
        select 'U 6' from dual union all
        select 'R 14' from dual union all
        select 'D 4' from dual union all
        select 'U 16' from dual union all
        select 'L 18' from dual union all
        select 'U 6' from dual union all
        select 'R 18' from dual union all
        select 'L 3' from dual union all
        select 'U 12' from dual union all
        select 'R 2' from dual union all
        select 'D 9' from dual union all
        select 'U 6' from dual union all
        select 'R 11' from dual union all
        select 'L 2' from dual union all
        select 'D 11' from dual union all
        select 'U 11' from dual union all
        select 'D 16' from dual union all
        select 'L 17' from dual union all
        select 'U 18' from dual union all
        select 'D 7' from dual union all
        select 'R 12' from dual union all
        select 'D 2' from dual union all
        select 'L 9' from dual union all
        select 'R 4' from dual union all
        select 'L 3' from dual union all
        select 'R 3' from dual union all
        select 'U 17' from dual union all
        select 'L 15' from dual union all
        select 'R 12' from dual union all
        select 'U 16' from dual union all
        select 'L 12' from dual union all
        select 'U 2' from dual union all
        select 'L 8' from dual union all
        select 'D 3' from dual union all
        select 'L 10' from dual union all
        select 'U 11' from dual union all
        select 'L 2' from dual union all
        select 'D 18' from dual union all
        select 'R 1' from dual union all
        select 'D 2' from dual union all
        select 'R 5' from dual union all
        select 'D 9' from dual union all
        select 'L 15' from dual union all
        select 'D 8' from dual union all
        select 'L 18' from dual union all
        select 'D 7' from dual union all
        select 'L 16' from dual union all
        select 'R 2' from dual union all
        select 'U 17' from dual union all
        select 'L 14' from dual union all
        select 'R 11' from dual union all
        select 'D 2' from dual union all
        select 'U 12' from dual union all
        select 'L 5' from dual union all
        select 'D 6' from dual union all
        select 'R 17' from dual union all
        select 'L 7' from dual union all
        select 'U 10' from dual union all
        select 'R 1' from dual union all
        select 'L 17' from dual union all
        select 'R 12' from dual union all
        select 'U 2' from dual union all
        select 'D 4' from dual union all
        select 'U 13' from dual union all
        select 'D 11' from dual union all
        select 'U 16' from dual union all
        select 'L 4' from dual union all
        select 'R 10' from dual union all
        select 'U 3' from dual union all
        select 'R 14' from dual union all
        select 'U 16' from dual union all
        select 'L 15' from dual union all
        select 'U 10' from dual union all
        select 'L 12' from dual union all
        select 'U 19' from dual union all
        select 'L 19' from dual union all
        select 'R 15' from dual union all
        select 'L 3' from dual union all
        select 'U 6' from dual union all
        select 'R 19' from dual union all
        select 'L 14' from dual union all
        select 'R 4' from dual union all
        select 'L 6' from dual union all
        select 'R 5' from dual union all
        select 'L 17' from dual union all
        select 'U 15' from dual union all
        select 'L 6' from dual union all
        select 'D 11' from dual union all
        select 'U 7' from dual union all
        select 'L 2' from dual union all
        select 'R 8' from dual union all
        select 'U 8' from dual union all
        select 'R 16' from dual union all
        select 'L 4' from dual union all
        select 'U 19' from dual union all
        select 'D 9' from dual union all
        select 'L 15' from dual union all
        select 'D 15' from dual union all
        select 'L 16' from dual union all
        select 'D 15' from dual union all
        select 'L 9' from dual union all
        select 'R 5' from dual union all
        select 'L 10' from dual union all
        select 'U 4' from dual union all
        select 'R 15' from dual union all
        select 'U 1' from dual union all
        select 'D 4' from dual union all
        select 'U 18' from dual union all
        select 'R 18' from dual union all
        select 'L 1' from dual union all
        select 'U 18' from dual union all
        select 'R 8' from dual union all
        select 'L 11' from dual union all
        select 'R 12' from dual union all
        select 'U 3' from dual union all
        select 'R 16' from dual union all
        select 'D 17' from dual union all
        select 'R 2' from dual union all
        select 'L 18' from dual union all
        select 'D 9' from dual union all
        select 'R 5' from dual union all
        select 'U 13' from dual union all
        select 'R 12' from dual union all
        select 'U 5' from dual union all
        select 'R 6' from dual union all
        select 'U 18' from dual union all
        select 'R 5' from dual union all
        select 'D 1' from dual union all
        select 'L 8' from dual union all
        select 'D 6' from dual union all
        select 'L 16' from dual union all
        select 'D 19' from dual union all
        select 'L 16' from dual union all
        select 'R 10' from dual union all
        select 'L 9' from dual union all
        select 'U 17' from dual union all
        select 'D 19' from dual union all
        select 'R 6' from dual union all
        select 'D 15' from dual union all
        select 'R 4' from dual union all
        select 'U 19' from dual union all
        select 'D 16' from dual union all
        select 'R 13' from dual union all
        select 'U 5' from dual union all
        select 'R 10' from dual union all
        select 'U 16' from dual union all
        select 'D 4' from dual union all
        select 'U 19' from dual union all
        select 'R 17' from dual union all
        select 'L 11' from dual union all
        select 'U 4' from dual union all
        select 'L 1' from dual union all
        select 'U 9' from dual union all
        select 'R 16' from dual union all
        select 'L 6' from dual union all
        select 'U 12' from dual union all
        select 'D 9' from dual union all
        select 'L 9' from dual union all
        select 'R 3' from dual union all
        select 'U 15' from dual union all
        select 'R 18' from dual union all
        select 'D 4' from dual union all
        select 'U 19' from dual union all
        select 'R 8' from dual union all
        select 'L 3' from dual union all
        select 'U 5' from dual union all
        select 'D 18' from dual union all
        select 'R 18' from dual union all
        select 'D 17' from dual union all
        select 'L 18' from dual union all
        select 'R 15' from dual union all
        select 'U 12' from dual
    ),
    set_up as (
        select 
            row_number()over(order by 1) as move_no,
            substr(moves, 1, 1) as directions,
            substr(moves, 3, length(moves)) as steps
        from  
            raw_input
    ),
    breakup as (
        select 
            row_number() over(order by d.move_no, d.step_no) as row_no,
            d.*
        from
            set_up a
        cross apply (
            select
                level as step_no,
                1 as individual_step,
                c.*
            from
                ( select * from set_up b where a.move_no = b.move_no ) c
            connect by 
                level <= c.steps
        ) d
    )
    select * from breakup
;

-- 2. Set up the head positions

drop table head_positions purge;
create table head_positions as 
    select 
        0 as pos_no,
        0 as x,
        0 as y
    from
        dual 
;

-- 3. Set up the tail positions

drop table tail_positions purge;
create table tail_positions as 
    select 0 as pos_no, 1 as tail_no, 0 as x, 0 as y from dual union all 
    select 0 as pos_no, 2 as tail_no, 0 as x, 0 as y from dual union all
    select 0 as pos_no, 3 as tail_no, 0 as x, 0 as y from dual union all
    select 0 as pos_no, 4 as tail_no, 0 as x, 0 as y from dual union all
    select 0 as pos_no, 5 as tail_no, 0 as x, 0 as y from dual union all
    select 0 as pos_no, 6 as tail_no, 0 as x, 0 as y from dual union all
    select 0 as pos_no, 7 as tail_no, 0 as x, 0 as y from dual union all
    select 0 as pos_no, 8 as tail_no, 0 as x, 0 as y from dual union all
    select 0 as pos_no, 9 as tail_no, 0 as x, 0 as y from dual
; 

--- 4. Set up the main procedure

declare
    last_head_x number;
    last_head_y number;
    leading_tail_x number;
    leading_tail_y number;
    last_tail_x number;
    last_tail_y number;
    cur_tail_x number;
    cur_tail_y number;
begin 
    /* Set up a cursor for loop on the moves table, for each move there's */
    for c1 in ( select * from moves ) loop    
        /* 1. Update the position of the head according the moves */
        select x, y into last_head_x, last_head_y from head_positions where pos_no = c1.row_no - 1;
        insert into head_positions values(c1.row_no, last_head_x , last_head_y);
        commit;
        case c1.directions
            when 'R' 
            then update head_positions set x = last_head_x + 1 where pos_no = c1.row_no;
            when 'L'
            then update head_positions set x = last_head_x - 1 where pos_no = c1.row_no;
            when 'U'
            then update head_positions set y = last_head_y + 1 where pos_no = c1.row_no;
            when 'D'
            then update head_positions set y = last_head_y - 1 where pos_no = c1.row_no;
        end case;
        commit;
        
        /* 2. For each of the 9 tails, upate their position according to the tail in front. */
        for i in 1..9 loop
            /* 2a. First, get the latest position of the tail */
            select x, y into last_tail_x, last_tail_y from tail_positions where tail_no = i and pos_no = c1.row_no - 1;
            /* 2b. Then, get the position of the tail in front - if it's the first tail, what's in front will naturally be the head */
            if i = 1 then 
                select x, y into leading_tail_x, leading_tail_y from head_positions where pos_no = c1.row_no;
            else
                select x, y into leading_tail_x, leading_tail_y from tail_positions where tail_no = i - 1 and pos_no = c1.row_no;
            end if;
            /* 2c. Insert a new row for the tail for subsequent update */
            insert into tail_positions(pos_no, tail_no, x, y) values(c1.row_no, i, last_tail_x , last_tail_y); 
            commit;
            
            /* 2d. Decide whether the position of the current tail should be moved. */
            if abs(leading_tail_x - last_tail_x) <= 1 and abs(leading_tail_y - last_tail_y) <= 1 then 
                continue; 
            end if;
            /* 2e. Decide whether to add 1 or minus one to the position */
            if leading_tail_x <> last_tail_x then
                case 
                    when leading_tail_x - last_tail_x > 0  
                    then cur_tail_x := last_tail_x + 1;
                    when leading_tail_x - last_tail_x < 0 
                    then cur_tail_x := last_tail_x - 1;
                end case; 
            else 
                cur_tail_x := last_tail_x;
            end if;
            
            if leading_tail_y <> last_tail_y then
                case 
                    when leading_tail_y - last_tail_y > 0  
                    then cur_tail_y := last_tail_y + 1;
                    when leading_tail_y - last_tail_y < 0 
                    then cur_tail_y := last_tail_y - 1;
                end case;
            else 
                cur_tail_y := last_tail_y;
            end if;
            
            /* 2f. Update the current position the tail */
            update tail_positions set x = cur_tail_x, y = cur_tail_y where tail_no = i and pos_no = c1.row_no;
            commit;
        end loop;
    end loop;
end;
/

--- 5. Part 1 

with distinct_last_tail as (
    select 
        distinct 
        x, y 
    from
        tail_positions
    where
        tail_no = 1
)
select count(*) from distinct_last_tail;

--- 5. Part 2 

with distinct_last_tail as (
    select 
        distinct 
        x, y 
    from
        tail_positions
    where
        tail_no = 9
)
select count(*) from distinct_last_tail;

